### ISSUE TITLE
why not write css in js?

### ISSUE THREAD

**Issue by tinybug** [mxstbr/react-boilerplate#1002]
Why not write css in js just like material-ui do? If so, I think the components will more easier compatible with others and you don't need to worry about the css config in webpack.

**Comment by peter-mouland** [comment]
how do you do things like `:nth-child(odd)` in css or `:hover`?

**Comment by GGAlanSmithee** [comment]
@peter-mouland selectors which affect the state of an element (`:active`, `:hover` etc) is supported if you use a framework like [radium](https://github.com/FormidableLabs/radium):

```javascript
const style = {
    backgroundColor: 'blue',
    ':active': {
        backgroundColor: 'green'
    }
}
```

child selectors, such as `:nth-child(odd)`, are not needed with inline css, since you have the entire JS syntax at hand, anything you can do in CSS you can do in JS and more.

There are some real painpoints with inline CSS though. The major one for me have been writing media queries. While it is supported in radium, it is just logically "weird" since you have to write the media queries per component.

**Comment by peter-mouland** [comment]
it sounds like a lot of extra work the browser has to do for something that comes in-built.
I wouldn't want to _have_ to use JS logic when you get it for free in CSS.

Also, having to learn another framework would not be something I'd be interested in unless there were clear benefits.  I.e. I use Sass; what do these frameworks do that I am missing from Sass?

The media query is a great point. I'd be interested to see the new proposed syntax for that.  

I write my css per component anyway, and i like the separation. i.e. my component structure : 

```
./component
├── component.js
├── component.scss
└── component.spec.js
```

**Comment by tinybug** [comment]
@peter-mouland please check out the follow links, you can see it's easy to handle your problem, and if you write css in js, you can also easy to move your components to react-native.

https://speakerdeck.com/vjeux/react-css-in-js-react-france-meetup
https://speakerdeck.com/vjeux/react-css-in-js

**Comment by mxstbr** [comment]
Done as of #1110! Enjoy!
