### ISSUE TITLE
Development With ServiceWorkers

### ISSUE THREAD

**Issue by ootoovak** [mxstbr/react-boilerplate#102]
In the ReadMe it is not clear what the development cycle is with the default ServiceWorker setup. After the first page load everything seems to be cached and a page refresh does not reflect any changes in the components.

After trying to figure it out I have resorted to just [removing the ServiceWorker setup](https://github.com/mxstbr/react-boilerplate#removing-offline-access). I figure there must be a better way than removing the configs for development and restoring it for production. Any chance someone could help me in figuring it out and maybe we can add it to the ReadMe?

**Comment by mxstbr** [comment]
Hey ootoovak, thanks for submitting this bug!

Could you tell me which browser you're using, and if you're using the `v3.0.0` or the `master` branch? On `master`, the problem is the AppCache that's very persistent in its caching, which the ServiceWorker shouldn't be. This is solved in v3, which you can get by running `git checkout v3.0.0` in your clone repo folder.

----

*Note:*

*Only loading the ServiceWorker in production would be as easy as wrapping the `navigator.serviceworker.register` in the `app.js` in this:*

```JS
if (process.env.NODE_ENV === "production")
```

*which, to be honest, sounds like a good idea, so I'll implement that! Thanks for the tip!*

**Comment by ootoovak** [comment]
Ah, I was using the `master` branch. I'll be sure to checkout `v3.0.0` instead. :+1: 

Also, thanks for the changes to the code and ReadMe and all the work you have done on this project so far. :smile:

**Comment by mxstbr** [comment]
@ootoovak Thank Samson, that is very much appreciated. I hope you enjoy `v3.0.0`, I'm going to assume this problem is fixed there. If it reappears on `v3.0.0`, feel free to reopen this issue!
