### ISSUE TITLE
Discussion: Balance of Opinionated Features

### ISSUE THREAD

**Issue by amilajack** [mxstbr/react-boilerplate#1028]
A lot of the issues in this project are 'add x feature because of y reason'. While it is good to add support for certain modules/technologies out of the box, I think there should to be a balance.

**Question for Discussion:**
1. How do we determine which modules/technologies should be unopinionated and opinionated?
2. Should we make a list of features that will will/not be added?

**Comment by gihrig** [comment]
I think the issue is at least partially  covered in [CONTRIBUTING.md Feature Requests](https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

> Feature requests are welcome. But take a moment to find out whether your idea fits with the scope and aims of the project. It's up to you to make a strong case to convince the project's developers of the merits of this feature. Please provide as much detail and context as possible.

I think this could be improved in a few ways:

1. Expand on and clarify the "scope and aims of the project" in this paragraph.
2. Move CONTRIBUTING.md back to the project root. @mxstbr Do you know why it's in `.github`? Does it ever 'magically' appear from this location?
3. Reference CONTRIBUTING.md#feature-requests from `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md`
