### ISSUE TITLE
[Question] How do I test Component applied styles 

### ISSUE THREAD

**Issue by pyjac** [mxstbr/react-boilerplate#1061]
I have the below component
```js
import React, { PropTypes } from 'react';
import cx from 'classnames';
import styles from './styles.css';

function Action({ ...props }) {
  const { disabled, action, type } = props;
  let styling;
  switch (type) {
    case 'success':
      styling = styles.success;
      break;

    case 'warning':
      styling = styles.warning;
      break;

    default:
      styling = styles.accept;
      break;
  }
  return (
    <button
      className={cx(styling, styles.action)}
      onClick={(e) => { e.preventDefault(); action(); }}
      disabled={disabled}
    />
  );
}

Action.propTypes = {
  action: PropTypes.func.isRequired,
  disabled: PropTypes.bool.isRequired,
  type: PropTypes.string,
};

export default Action;
```
I believe while running test the loader for `.css` returns an empty object. 
How do I test that the styles from `./styles.css` is applied correctly when different type values are passed. 

Here is what I have though
```js
describe('<Action />', () => {
  it('should render when type is not specified', () => {
    const renderedAction = renderAction({ disabled, action });
    expect(renderedAction).toExist();
  });

  it('should render when `type` is `success`', () => {
    const type = 'success';
    const renderedAction = renderAction({ disabled, action, type });
    expect(renderedAction).toExist();
  });

  it('should render when `type` is `warning`', () => {
    const type = 'warning';
    const renderedAction = renderAction({ disabled, action, type });
    expect(renderedAction).toExist();
  });

  it('should handle click events', () => {
    const onClickSpy = expect.createSpy();
    const renderedAction = renderAction({ action: onClickSpy, disabled });
    renderedAction.find('button').simulate('click', { preventDefault() {} });
    expect(onClickSpy).toHaveBeenCalled();
  });
});
```

**Comment by peter-mouland** [comment]
I'd say testing for classNames/styles that haven't had any logic applied to them is going to cause more problems than it solved.  

This is because every time you decide to refactor the styling (i.e. improving standards or dropping old browser support) your tests will fail even though the components look and feel hasn't changed.  This will cause people to not read the test or think about the change and you'll end up with loads of passing tests that don't actually tell you anything.  

If the classname/style has been applied because of some logic (i.e. show/hide) then I think thats worth unit testing.

If it is the look of the component you want to test I'd go for 'regression testing' approach and take screen shots of your component using something like Nightwatch and then using Resemble.js compare them to ensure nothing has changed.  This coupled with browserstack/SauceLabs means you'll also be able to test multiple browsers.

**Comment by mxstbr** [comment]
Exactly what @peter-mouland said. Amazing answer!
