### ISSUE TITLE
mainFields breaks libraries with browser field in package.json

### ISSUE THREAD

**Issue by esbenp** [mxstbr/react-boilerplate#1098]
# React Boilerplate

## Issue Type

Bug

## Description

In the [Webpack config](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L91) `mainFields` seems to be breaking libraries such as `isomorphic-fetch`. This is because when loaded in the browser the `main` field of `isomorphic-fetch` is used. However, `isomorphic-fetch`'s `package.json` is defined as.

```
{
  "browser": "fetch-npm-browserify.js",
  "main": "fetch-npm-node.js",
}
```
So the node version of the library is loaded because of `mainFields`. This breaks in the browser. This is relevant to this boilerplate as very popular libraries such as [redux-api-middleware](https://github.com/agraboso/redux-api-middleware/blob/master/src/middleware.js#L1) use `isomorphic-fetch` for requests. 

The error is
```
index.js:27Uncaught TypeError: inherits is not a function
```

I am fairly new to Webpack so I apologize if I have overlooked something. As to the fix, I am not sure but maybe change `mainFields` to something like

```
mainFields: [
    'browser',
    'jsnext:main',
    'main'
]
```

## Steps to reproduce

* Require `isomorphic-fetch`
* Open in browser

# Versions

- Node/NPM: 6.2.1
- Browser: Chrome 53.0.2785.143 (64-bit)

**Comment by amilajack** [comment]
Haven't messed around with `mainFields` before. Ping @mxstbr @gihrig

**Comment by esbenp** [comment]
For me this worked 
```
mainFields: [
    'browser',
    'jsnext:main',
    'main'
]
```

but I am unsure of the consequences of this. Alternatively, I saw somewhere a guy did something a long the lines of
```
mainFields: isServer()
    ? ['jsnext:main', 'main']
    : ['browser', 'jsnext:main', 'main']
```

But I guess that would require the `mainFields` config to be used at runtime and I do not know if it does..?

**Comment by andykenward** [comment]
It isnt a bug as [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch#isomorphic-fetch-) is built to work with `node` and `Browserify`.

If you look at the code for `isomorphic-fetch` it is just adding [`fetch`](https://github.com/github/fetch) as a global for client side. Which is already [done in the boilerplate](https://github.com/mxstbr/react-boilerplate/blob/8693af3708e31f25fc0883256da605b3ccc03c9a/internals/webpack/webpack.base.babel.js#L62)

So you could just use [`fetch`](https://github.com/github/fetch) instead of [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch)?

Also instead of using [`redux-api-middleware`](https://github.com/agraboso/redux-api-middleware) you can use [`redux-saga`](https://github.com/yelouafi/redux-saga) + [`fetch`](https://github.com/github/fetch). Check out the [example](https://github.com/mxstbr/react-boilerplate/blob/8693af3708e31f25fc0883256da605b3ccc03c9a/app/containers/HomePage/sagas.js#L16-L29) request in the boilerplate.

**Comment by esbenp** [comment]
Okay, but `redux-api-middleware` was just an example of a library where this problem occurs. I suppose there will be others when Webpack respects the `browser` field.

If we look at Webpack 1 configuration the equivalent of `mainFields` is `packageMains` and its default value is `["webpack", "browser", "web", "browserify", ["jam", "main"], "main"]`

So I guess the default `mainFields` in Webpack 2 is something similar except it is overridden in this boilerplate configuration.

**Comment by andykenward** [comment]
@esbenp does #1054  close this issue?

**Comment by esbenp** [comment]
Oh yeah it does. I was not able to find a similar issue when searching but this is definitely a duplicate of #1046. Thanks @andykenward I will close this one.
