### ISSUE TITLE
Hangs on large images

### ISSUE THREAD

**Issue by haf** [mxstbr/react-boilerplate#1127]
## Issue Type

- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

You can't do a development flow in this repo when you have large images as part of the source. The subscription to the hmr websocket never returns.

## Steps to reproduce

Reference a 4MiB large jpg from css. Watch the incremental compiler hang (AFAIK, I have not waited forever, and there are no progress bars displayed).

## Suggested fix

Remove the PostCSS dependency until it's mature.

# Versions

`npm install` from this repo. 

NPM: 3.8.3
Browser: FF, Chromium, Safari.

**Comment by oliverturner** [comment]
@haf PostCSS is perfectly mature and nothing to do with your issue.

If you can produce a limited test case that shows your workflow functioning as you expect with a raw Webpack/HMR implementation I'll reopen this issue.

**Comment by haf** [comment]
Sure. One sec.

**Comment by haf** [comment]
Here's a complete sample that works with stylus-only, importing `background.jpg`. Replacing stylus with the default postcss config in this repo makes it hang. https://github.com/haf/optimistic

**Comment by oliverturner** [comment]
I'm afraid I can't reproduce your issue. Everything works fine with PostCSS: loading the 4.2mb png, the 187 Kb image, HMR, etc.

The main difference I can see between your repo and RBP is that you've removed the optimisation processing from here:
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L46

This would seem to be the culprit, since re-adding it triggers your issue.

Ultimately, this project is intended to be a boilerplate for _your_ code: if Stylus works for you, that's great.

**Comment by haf** [comment]
Thanks Oliver for trying to reproduce. I'm happy you managed to reproduce the issue.

I've renamed issue to be more accurate so that's it's more obvious what's fixed when it's fixed.

**Comment by oliverturner** [comment]
Right, but this isn't an issue that needs to be "fixed" because nothing's actually broken: 

- This configuration works well for normal usage.
- In your case, the jpg is visually identical to the png and works fine with the optimisations restored.
- If you _really_ want to load a 4.2Mb background image, you are able to make the adjustments you need  to do so.

If you were suggesting adding a caveat to the docs saying "use the appropriate filetype: over-large files will cause issues", I'd consider a PR, but I don't consider this a bug.

**Comment by haf** [comment]
4.2 MiB isn't very large. The source image in Photoshop is 172 MiB, so it's arguably normal usage.

I know the JPEG is visually identical, I created it ;) I'm good, aren't I?


The issue is that **everything just hangs without any message** as to what it can be that's broken. If there's a progress or a log stating that JS is trying to optimise my image, then it would make more sense.

If you consider hanging without output working well, then this is a non-issue.

Cheers
