### ISSUE TITLE
react-icons lib not working

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1131]
My code:

```
import React, { Component, PropTypes, Children } from 'react';
import styles from './styles.css';
import NavBar from '../NavBar';
import { FaBeer } from 'react-icons/lib/fa/';

export default class App extends Component {
  render() {
    return (
      <div className={styles.container}>
        <FaBeer />
        {Children.toArray(this.props.children)}
      </div>
    );
  }
}
```

This approach should work according to below comment/issue:
https://github.com/mxstbr/react-boilerplate/issues/943#issuecomment-245089173

Error message: 

```
ERROR in ./~/react-icon-base/index.js
Module parse failed: /home/x/Desktop/repos/frontend/node_modules/react-icon-base/index.js Unexpected token (3:50)
You may need an appropriate loader to handle this file type.
| import { default as React, PropTypes } from 'react'
| 
| const IconBase = ({ children, color, size, style, ...props }, { reactIconBase = {} }) => {
|   const computedSize = size || reactIconBase.size || '1em'
|   return (
 @ ./~/react-icons/lib/fa/500px.js 18:15-41
```

**Comment by sedubois** [comment]
In both your example and in [there](https://github.com/mxstbr/react-boilerplate/issues/943#issuecomment-244309765), looks like it doesn't recognise the `...` object rest properties. I think it needs to be enabled using [Babel](https://babeljs.io/docs/plugins/transform-object-rest-spread/).

**Comment by elswenson** [comment]
@williamgranli This is something that it seems many react-icons users have run into, I would suggest looking there for answers. The most common solution that I have seen is to add a few lines to the webpack config (for this boilerplate in particular, the base webpack config). 

If you look at [an old react-icons issue](https://github.com/gorangajic/react-icons/issues/34), with the state the library is currently in, your imports from react-icons need to be loaded with babel-loader, rather than a file loader, or at least that has been my simplest go-to on small projects thus far. 

I admittedly do not understand the process well enough to tell if this is an unnecessary work-around (i.e. if there is a significantly better way of doing it).
