### ISSUE TITLE
Redux-observable

### ISSUE THREAD

**Issue by sedubois** [mxstbr/react-boilerplate#1139]
Netflix's new [redux-observable](https://redux-observable.js.org/) library looks quite promising (hah) to handle async state by integrating Redux's pure state change logic with [RxJS](https://github.com/Reactive-Extensions/RxJS) observables taking care of the side-effects. Observables offer two main advantages compared to Promises:
- side-effects are automatically cancellable, no need to manually handle subscription lifecycle
- can stream any number of events (promises succeed/fail only exactly once)

Besides bringing the principles of functional reactive programming, it can integrate with various other observable streams and languages.

In general, starting afresh, do you think redux-observable is the way to go and the future of async state management 👍 or is redux-saga the superior choice 👎 ? Why?

There is a proposal to add Observables within ES like was done for Promises. I'm not aware of syntax sugar like the yield/*/async/await available for Promises, though.

One side-question I have is, how well would this integrate with code dealing with GraphQL APIs (now and in the future)? I guess they are synchronized through the Store or combined within each Component.

[More learning](https://www.learnrxjs.io/) on RxJS.

<div align="center">
  <img src="http://reactivex.io/assets/Rx_Logo_S.png" />
  <img src="https://redux-observable.js.org/logo/logo-small.gif" width="100px" />
</div>

**Comment by sourcesoft** [comment]
> There is a proposal to add Observables within ES like was done for Promises. I'm not aware of syntax sugar like the yield/*/async/await available for Promises, though.

https://www.youtube.com/watch?v=DqMFX91ToLw
Syntax is close to that on top of generators.

also an awesome talk about redux-observable: https://www.youtube.com/watch?v=AslncyG8whg

**Comment by Dattaya** [comment]
> There is a proposal to add Observables within ES like was done for Promises.

We'll have to wait for it a little longer, because it's not going to make it into ES2017 (ES8).

> One side-question I have is, how well would this integrate with code dealing with GraphQL APIs

Depends on the client. Apollo has some interoperability with observable libs judging from this commit: https://github.com/apollostack/apollo-client/pull/196/files#diff-3e9523eee379c5b7eca8da84dae6bbe5R398  

I also have a side-question, what is the final size going to be when we combine all of this: React, GraphQL client, RxJS, redux-observable, redux.

**Comment by sedubois** [comment]
> what is the final size going to be

Good question, I guess same as for any other library it needs to be bundled properly and the size is justified if it brings new valuable functionality that benefits UX and DX.

RxJS [docs](https://github.com/ReactiveX/rxjs) show the methods can be imported individually (e.g `import { of } from 'rxjs/observable/of'`). I threw the [question](https://github.com/redux-observable/redux-observable/issues/132#issuecomment-255742370) at redux-observable. That link also discusses allowing other (potentially smaller) observable libraries than RxJS.

**Comment by Dattaya** [comment]
> RxJS docs show the methods can be imported individually (e.g import { of } from 'rxjs/observable/of'). 

Hopefully tree shaking solves this problem, rxjs core.

> threw the question at redux-observable

Thanks for asking it, I was reading that topic when you posted a new message.

> I guess same as for any other library it needs to be bundled properly and the size is justified if it brings new valuable functionality that benefits UX and DX.

There has to be a limit, GraphQL clients are positioned as mobile friendly as we get exactly what was asked for, but initial load and evaluation of all that js is going to ruin it.
Another issue is that learning curve of GraphQL + reactive programming is going to be even higher than sagas + GraphQL.

**Comment by sedubois** [comment]
@Dattaya 

> Hopefully tree shaking solves this problem

Is tree shaking already effective in RBP? If not, what kind of effort would it require (I'm new to this subject, but it looks indeed like what this needs)?

> initial load and evaluation of all that js is going to ruin it

Netflix developed redux-observable and they have like 70 million users across all platforms, so they might have managed to make it mobile-friendly too?

> Another issue is that learning curve of GraphQL + reactive programming is going to be even steeper than sagas + GraphQL

Coming from not knowing sagas two weeks ago, I don't see why observables would be more complex to learn. Well, I just don't have enough perspective to opinate on learning curves at this point.

@sourcesoft 

> https://www.youtube.com/watch?v=DqMFX91ToLw
> Syntax is close to that on top of generators.

Thanks for the video! The proposed `for (... on ...)` syntax looks quite nice, but `async function*` looks a bit scary 😉 Anyway it looks like this [proposal](https://github.com/jhusain/asyncgenerator) was rejected and instead there would be the more limited [Observable](https://github.com/tc39/proposal-observable). @Dattaya where do you track which features make it into which ES version?

To come back to redux-observable, yes their intro video is great, that's how I learned about it. Supposing it's not too heavy client-side, it still looks like something valuable to learn at this point.

**Comment by Dattaya** [comment]
> Is tree shaking already effective in RBP? If not, what kind of effort would it require (I'm new to this subject, but it looks indeed like what this needs)?

I was just agreeing with your argument about `import { of } from 'rxjs/observable/of'` because I thought it only works for such imports based on another (I don't have a link) discussion on github, but it seems it works even with imports like these: `import { add } from './math';` ([see examples from the docs]( https://github.com/webpack/webpack/tree/master/examples/harmony-unused)) I don't know if tree shaking is working right now, maybe @mxstbr can clarify this.

"ruin it" was too strong wording, because browser caches it, and I was talking generally that it's good to measure the end result. Relay1 + RxJS + everything else could be too much (I don't know whether Netflix uses it); maybe some tricks could be applied to reduce overall size of the library.

> where do you track which features make it into which ES version?

Usually a new spec is frozen (new features can't be added) in January-February and released in June-July (year == version of ES, e.g. ES2017). [Finalized proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md) guaranteed to be included in the spec, [level 4 proposal](https://github.com/tc39/proposals) have high chance to make it (currently I don't see any). Observable is level 1 now, it doesn't have a rocket icon next to it meaning it's not ready yet to transfer to the next stage:

![image](https://cloud.githubusercontent.com/assets/387256/19656036/e457d234-9a26-11e6-9547-70b5b23051b6.png)

There are two more pages: [Stage 0 proposals](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md) and [Inactive proposals](https://github.com/tc39/proposals/blob/master/inactive-proposals.md).

**Comment by sedubois** [comment]
From this webpack [issue](https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2/issues/3), it looks like tree shaking isn't working at all currently (webpack 2 is still beta). (It apparently works in rollup.)

@Dattaya 

> Relay1 + RxJS + everything else could be too much

Yes and actually adding Relay 1 makes it [20% of project size](https://github.com/mxstbr/react-boilerplate/pull/1065#issuecomment-255804606), bigger than React.

And thanks for the links 😊

**Comment by jayphelps** [comment]
> Hopefully tree shaking solves this problem.

Tree shaking of any existing method (rollup/webpack2) will provide negligible benefits to RxJS. [Full details here](https://github.com/ReactiveX/rxjs/issues/1671#issuecomment-252129235). tl;dr you cannot tree shake methods on object prototypes. Using operator patching or [importing operator references directly](https://github.com/ReactiveX/rxjs/pull/2034) are the two ways to keep the bundle size down.

Without context around whether this has already been discussed, I did want to slip in a opinion: Bringing in something like redux-observable (or redux-saga) shouldn't be taken lightly. Both have steep learning curves and not every app needs this sort of complex side effect management. Same goes for bringing in redux itself as well. We need to be good stewards to not fatigue people implying that these things are _necessary_ to write a React app.

[Here's a quote from our docs:](https://redux-observable.js.org/docs/basics/Epics.html)

> redux-observable (because of RxJS) truly shines the most for complex async/side effects. If you're not already comfortable with RxJS you might consider using redux-thunk for simple side effects and then use redux-observable for the complex stuff. That way you can remain productive and learn RxJS as you go. redux-thunk is much simpler to learn and use, but that also means it's far less powerful. Of course, if you already love Rx like we do, you will probably use it for everything!

**Comment by sedubois** [comment]
Thanks @jayphelps. The only reason I brought the subject is because RBP already uses redux-saga, and wanted to see if it made sense to "replace" it with redux-observable.

**Comment by Telemakhos** [comment]
> Bringing in something like redux-observable (or redux-saga) shouldn't be taken lightly. Both have steep learning curves and not every app needs this sort of complex side effect management. Same goes for bringing in redux itself as well. 

Finally some common sense...

**Comment by sedubois** [comment]
Thanks for the discussion, I'll close this but feel free to add comments

**Comment by mxstbr** [comment]
Just to note this here, we've been using webpack v2 with tree shaking for a few months now, that's a thing!

**Comment by sammy6464** [comment]
Hi I just wanted to chime in as I was literally laying in bed last night thinking about this haha. I just wanted to suggest that Redux Observable and RXJS are possibly a more 'future proof' and scalable solution for the reason that reactive extensions patterns can be implemented in (currently) 15 languages! So organisations can have server side and client side implementations that map to each other more logically, or at least common patterns that can be understood by future staff, subcontractors etc..

Don't get me wrong I think Redux Saga is brilliant for what it does, but I can't help but feel it is one of those 'in between' technologies that is applicable for a certain time, and then once it's made redundant (which I believe will happen soon-ish as Observables become more ubiquitous) the learnings and nuances of it go away with it as they are unique to Redux Saga. In contrast, taking the equivalent time to learn and become familiar with RX will as I say enable patterns that can be used throughout your entire stack.

Anyway just my 2c, I totally understand the logic of using redux saga as it's battle tested and people are (somewhat) familiar with it, but I just wanted to add some fuel to the observables fire :)

**Comment by davidwilde** [comment]
I've been reading up on RxJS and redux-observables and I would agree with SamMatthewsIsACommonName that redux-sagas seems like an inbetween technology because RxJS feels like something that can be reused for multiple uses. 

I am going to create a pull request for the boilerplate where redux-sagas are replaced with redux-observable so that it can be reasoned further
