### ISSUE TITLE
The version of eslint

### ISSUE THREAD

**Issue by bicycleChen** [mxstbr/react-boilerplate#1141]
## Issue Type
- [ ] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
(Install the packages via yarn`yarn install`) When I run `npm run build`, there gonna be an error above:
`
Configuration for rule "eol-last" is invalid:
`
and according to this [link](https://github.com/airbnb/javascript/issues/1088), we should change the version of eslint to `^3.6.0`

**Comment by gihrig** [comment]
package.json: `    "eslint": "3.8.0",` in dev branch.

Closing as "fixed in dev"

**Comment by mxstbr** [comment]
Wanna release a new version @gihrig?

**Comment by gihrig** [comment]
Been super busy with work lately. I don't have enough up-to-date experience with dev branch to say one way or the other. :-/

There are several open PRs that might be close to merge? Particularly #1076. #1032, what happened to #980 (was really looking forward to that), #931

But it has been a almost a month since 3.2.1 so it's about time 😄
