### ISSUE TITLE
Selectors not executing when I call them

### ISSUE THREAD

**Issue by williamgranli** [mxstbr/react-boilerplate#1217]
My selectors.js looks like this: 

```
const selectMyIntegrationsPageDomain = () => state => state.get('myIntegrationsPage');

const selectId = () => createSelector(
  selectMyIntegrationsPageDomain(),
  (myIntegrationsPageState) => myIntegrationsPageState.get('id')
);
export {
  selectMyIntegrationsPageDomain,
  selectId,
};
```

I use them in my container (index.js), in the mapStateToProps function, which looks like this:

```
function mapStateToProps(state) {
  console.log(selectId());
  return {
    id: selectId(),
  };
}
```

Where selectId is imported from selectors.js. The props validation fails (expecting string but got fun) and the console.log on the first line of the mapStateToProps-function prints out the function body of the selector function. 

What am I doing wrong? As far as I can see I'm using the functions exactly as in the boilerplate project...

Thanks.

**Comment by Dattaya** [comment]
You don't use `createStructuredSelector` that does everything automatically, that means you should pass `state` into `selectId` yourself: `selectId()(state)` also `selectId()` should be assigned to a variable somewhere otherwise nothing will be memoized due to recreation of a memoized selector each time state or props change.
