### ISSUE TITLE
How to remove styled-components and replace with old behaviour?

### ISSUE THREAD

**Issue by tpinne** [mxstbr/react-boilerplate#1265]
How can I use the newest version of this boilerplate but without styled-components and use normal css-files as before?

I tried to add all loader configurations from version 3.2.1 but cannot get it to work.

**Comment by jeremyadavis** [comment]
Just had to work though this myself, it was a bit tedious but appears to have worked just fine.

Here's roughly the steps I did.

Did a file comparison/merge on my 3.2.1 repo against a 3.3.3 one on the following files:

- package.json
- all files in internals/webpack
- app/app.js
- app/store.js
- app/routes.js

In these files I made sure to keep any conflicts relating to css stuff e.g postcss, stylelint, ExtractTextPlugin.

The only real gotcha that arose was that webpack 2 will [error](https://github.com/postcss/postcss-loader/issues/92) due to how the [postcss options](https://github.com/mxstbr/react-boilerplate/blob/v3.2.1/internals/webpack/webpack.base.babel.js#L74) are configured.

In webpack.base.babel.js remove the postcss custom property
```
postcss: () => [
    postcssFocus(), // Add a :focus to every :hover
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
  ],
```
and move them to the LoaderOptionsPlugin within the plugins property
```
plugins: options.plugins.concat([
   ...
    new webpack.LoaderOptionsPlugin({
      options: {
        context: path.resolve(process.cwd()),
        postcss: [ 
          postcssFocus(), // Add a :focus to every :hover
          cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
            browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
          }),
          postcssReporter({ // Posts messages from plugins to the terminal
            clearMessages: true,
          }),
        ],
      },
    }),
  ]),
```

I think that was a majority of what I did and so now I can slowly migrate my current components over to styled-components styling if I wish. Plus I get the benefits of the core updates that also are in 3.3.3.

**Comment by carlos-peru** [comment]
@tpinne, why not having all your common files content in your app/global-styles.js? You can also add packaged modules in app/app.js. For instance if you want to include boostrap just:

import 'bootstrap/dist/css/bootstrap.css';

You might already know this, but dropping it in just in case. Plus, I do believe styled-components is a good practice because it lets your component be more composable.

**Comment by tpinne** [comment]
@jeremyadavis 
Thanks man, I didn't get my head around the postcss options problem. So I've been nearly close to the finish line.

@carlos-peru 
We are "updating" the boilerplate in an existing application. Therefore we want run the application with the minimum changes necessary in the first place. Then we might think of switching to styled components.

But for now writing styled components inside PHPStorm (our IDE of choice because we can code the complete application stack with it) would be a pain in the ass. No syntax checking or highlighting, no autosuggest and no emmet support. So somebody here would literally kill me if we make a hard cut here ;)

**Comment by ravindranpandu** [comment]
@tpinne did you manage to use the css files inside components now?

**Comment by CHRISTOPHERDIEHL** [comment]
Could you post your webpack config? I'm still having trouble with this @tpinne @jeremyadavis

**Comment by CHRISTOPHERDIEHL** [comment]
@tpinne  Would you mind posting a copy of your webpack config? I was able to get dev working, but the css isn't loading in prod.

**Comment by tpinne** [comment]
Sorry, haven't done any work on this myself largely because of a project stop. Can't help you at the moment.

**Comment by CHRISTOPHERDIEHL** [comment]
@tpinne all good mate, thanks for responding though

**Comment by jeremyadavis** [comment]
I'm mostly written off of css in favor of styled components, but here's the snippets in my prod webpack file incase they help

``` javascript
...
  cssLoaders: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    loader: 'css-loader?modules&-autoprefixer&importLoaders=1!postcss-loader',
  }),
...
new ExtractTextPlugin('[name].[contenthash].css'),
...
```

also, I don't use the OfflinePlugin due to my environment constraints so you might try temporarily disabling it if you're still having prod issues.

**Comment by CHRISTOPHERDIEHL** [comment]
@jeremyadavis  thanks for the help! I actually followed the same direction as you and have stopped using css in favor of styled components as well.

**Comment by jeremyadavis** [comment]
Yeah I'm really liking styled components, I just did the css stuff as a stop gap so I wouldn't have to convert 100s of components in one shot.

**Comment by somghosh** [comment]
hi @jeremyadavis 

I am upgrading from 3.0 to 3.4 , and it seems like in react-boilerplate currently I no longer have the flexilbity of putting a line like specifying `autoprefixer` configurations. Is this correct, as per your earlier exercise above? I am not sure where to put these lines - as cssnext is totally absent in 3.4 code

    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
              browsers: ['last 5 versions', 'IE > 8', 'Safari > 5', 'Firefox >= 25', 'iOS > 7'], // ...based on this browser list
              features: cssSettings,
            }),

**Comment by jeremyadavis** [comment]
I haven't gone to 3.4, so I don't know what all is different, but I imagine a good bit will be changed since it moved to Webpack 2.

I would urge you to embrace styled-components and try to convert off the css if it is feasible as they are much more robust. You might spend just as much time trying to get the css added back to webpack than to convert to styled-components.
