### ISSUE TITLE
getComponent and load reducer/sagas is called after updating query params

### ISSUE THREAD

**Issue by talbenbasat** [mxstbr/react-boilerplate#1282]
Hi,

I'm using the boilerplate - must say it's great.

In my project i'm updating the query params after change.
Im doing it using { push } action of react-router-redux.

The problem is, that the sagas and reducers are loaded multiple times.
a thing that make my api calls increase linearly.

I can patch it using  'takeLatest' for the sagas but It's just a patch.

any idea?

**Comment by sammy6464** [comment]
Hi @talbenbasat I think I'm having a similar program. I'm using push and its causing my sagas to kind of double up each time, dispatching 1 then 2 then 4 then 8 actions.  Is this the same as you experienced?

**Comment by gihrig** [comment]
@sammy6464 Because this is a somewhat old issue, I presume you have searched, but do either of these help? [#1188 (comment)](https://github.com/mxstbr/react-boilerplate/issues/1188#issuecomment-258409446) or [#1183 (comment)](https://github.com/mxstbr/react-boilerplate/issues/1183#issuecomment-265430691). Note that #1315 was not merged.

**Comment by sammy6464** [comment]
hey @gihrig  thanks yes sorry I didn't see those that's my same issue. Looks like I just wasn't understanding the cancel and locationchange API. Maybe the comment is somewhat confusing? " // Suspend execution until location changes ", I mean now in retrospect it makes perfect sense but maybe a short line could be added explaining that otherwise a new saga will begin when it's injected with the component leading to multiple sagas etc... Anyway my bad essentially. Thanks for finding those older issues!

**Comment by talbenbasat** [comment]
Hi @sammy6464 ,

Sorry i didnt post the answer.
But yes, we are suppose to place a watcher and cancel it after LOCATION_CHANGE

Good luck

**Comment by Jamakase** [comment]
Hi, guys. Looks like there are still some issues. If i am trying to open http://url/:id my sagas are injected twice and i am cancelling the watcher

`export function* watchGetConversationMessages() {
  const watcher = yield takeEvery(NEW_MESSAGES_REQUESTED, getConversationMessages);

  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}`

 but second request is still sent here. Any ideas?

**Comment by talbenbasat** [comment]
Hi @Jamakase,

Do you have the Redux-dev-tools in your chrome?

Can you please add a print screen of the dispatched ACTIONS.

Tal
