### ISSUE TITLE
Lodash more than 500Kb

### ISSUE THREAD

**Issue by zamrq** [mxstbr/react-boilerplate#1309]
based stats.json and WebPack analyze, lodash has 500KB more, while in the whole boilerpate is only used on some parts of the course. Is it not better to throw lodash at production level

**Comment by gihrig** [comment]
See #918 "How can I shrink the main.js build file?"

**Comment by jwinn** [comment]
@zamrq as @gihrig mentioned in an earlier comment on #918: `import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';` loads the whole file being required--found through [Node.js means](https://nodejs.org/api/modules.html#modules_file_modules). In this instance, this means the file `node_modules/lodash/lodash.js` i.e. all ~ 500K of it. Then the module is destructured accordingly. In order to reduce what's brought in, you correctly shifted your code to requiring only the lodash pieces in use--well that's not completely accurate, but close enough.

Packages like [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) and [webpack-lodash-plugin](https://www.npmjs.com/package/lodash-webpack-plugin) perform some implicit conversion/modification behind the scenes, during each respective process (babel transpilation and webpack compilation), to change the required lumpsome to use the specific pieces only (and other reduction in code size required, e.g. noop, identity, etc. implementations).

I prefer explicitly denoting which pieces I want from any given library/package, when available.
So my preferred method is to change `import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';` to:
```
import conformsTo from 'lodash/conformsTo';
import isEmpty from 'lodash/isEmpty';
import isFunction from 'lodash/isFunction';
import isObject from 'lodash/isObject';
import isString from 'lodash/isString';
```

As long as no one objects (@mxstbr, @gihrig, et al), I am going to make the change to the more explicit and specific approach outlined above (in both `app/utils/asyncInjectors.js` and `internals/templates/asyncInjectors.js`) and submit to the `dev` branch. From the bp perspective this will reduce the required lodash usage to it's roughly bare minimum. It does not preclude some consumer of the bp to include the entirety of the whole lodash npm package, but would at least show best practices when working with large packages that offer piecemeal inclusion.

**Comment by gihrig** [comment]
It's unfortunate that the destructuring approach seems to be the "ES6 way", according to popular blogs, examples etc., and it is nicer to compress several lines of code into one. I agree though, that we should not let the "[Good programmers write code that humans can understand.](https://en.wikiquote.org/wiki/Martin_Fowler#Refactoring:_Improving_the_Design_of_Existing_Code.2C_1999)" mantra be an excuse to throw out all concern for code size - size does matter, too.

While the final decision should depend on the project involved, I agree that this boilerplate should present this as a best practice, especially in this case.

**Comment by Geeman201** [comment]
@gihrig not seen that quote before but am a big fan of Martin Fowler! it's inline [with what uncle bob says with the boy scout rule](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)!

The more I code with ES6 the less I am finding [myself needing utility libraries like Lodash](https://www.sitepoint.com/lodash-features-replace-es6/).

Could a better solution here be to remove Lodash entirely. In this bootstrap it's only used for validation so feels superfluous to include the library at all?

**Comment by gihrig** [comment]
If someone would like to explore a plain ES6 solution that eliminates Lodash, that would be awesome!

**Comment by jwinn** [comment]
I will take a look at changing this. I do remember having a conversation with Max about using `lodash`, but if our only reason remains for `asyncInjectors.js` I feel it best for us to remove it if at all possible as it's then one less dependency. :-)

/cc @mxstbr

**Comment by gihrig** [comment]
Well, I should have done this before posting that comment, but lodash is used in several places.

A global search shows some 270 instances of "lodash" across 7 files. `yarn.lock` in particular shows 260 instances. 

I clearly don't understand the minutia of dependency management as it would apply here, but whatever is done should be supported by a demonstrated benefit. We might remove lodash from react-boilerplate proper, but yarn.lock makes it clear we will not be able to remove (the many versions! of) lodash form our dependencies.

It's probably worth noting that app/utils/asyncInjectors is the only file using lodash outside of `internals` or dependencies.

![image](https://cloud.githubusercontent.com/assets/1481063/20996408/35517232-bcb2-11e6-9ce8-138aa2fad6ac.png)

**Comment by jwinn** [comment]
Interesting. I hadn't had a chance to look into all occurrences of lodash in react-boilerplate, so I appreciate you doing that. I'm of the opinion to keep lodash and apply the changes in #1312. We could implement each of the 8 or so lodash functions--used directly in react-boilerplate--in an ES6 manner, but this would add functions we'd need to maintain--adding further complexity to the boilerplate--to gain only a modicum of size reduction.

Thoughts?

**Comment by gihrig** [comment]
Yeah, I think you're on the right track. At the very least, this approach demonstrates the issue and (with appropriate comment), users can take heed or ignore as they see fit.

**Comment by zamrq** [comment]
I think its clear
please find which one is best for you, if it really wants to eliminate lodash, please replace with plain ES6 for each function which is used as is told by @gihrig 

or otherwise use WebPack lodash plugin, it might be a bit lower the file size of your production level

**Comment by samit4me** [comment]
Did you close this on purpose? Anything to reduce filesize seems like a good enhancement!

**Comment by nhducit** [comment]
I wonder why does our boilerplate produce a too big main.js files. I just clone the boilerplate from main branch and run `npm run analyze`. And here is the result from `http://webpack.github.io/analyse` website.

It seems the main.js file import none compressed files.

![screen shot 2016-12-28 at 9 44 10 pm](https://cloud.githubusercontent.com/assets/4246176/21524230/1a6a51a0-cd47-11e6-88e6-39ad8ee99768.png)
