### ISSUE TITLE
Server return status 200 while rendering 404 page

### ISSUE THREAD

**Issue by fullyfaltu** [mxstbr/react-boilerplate#1409]
When I hit a not-found page, it gives me 200 response code instead of 404. How can I fix this issue?

**Comment by neverfox** [comment]
Only web servers can return status codes, not browser-based JS, and a basic server running this app doesn't know that not-found is special. You'd have to configure your server to do the right thing with that route.

**Comment by Schubbcasten** [comment]
That's because all requests incoming to the server that don't match a static resource a redirected by default to the index.html where the client side react router then does its magic. Thus the server will always return the index.html (thus with a code 200). The react-router on the client side then decides whether the URL matches one of his routes and then renders the according page. This is then by default the 404 page.

If you'd want another behavior you have to indeed configure the server accordingly. To properly achieve this behavior you would probably need to make your application universal (server-side-rendering #1236).

**Comment by neverfox** [comment]
Or at the very least, make your 404 page server-side and don't rewrite that path.
