### ISSUE TITLE
In the example why is repo data stored at the global scope?

### ISSUE THREAD

**Issue by kylesavant** [mxstbr/react-boilerplate#1412]
Here is what I see happening...

```
.In the HomePage container there is a saga (getRepos) that's responsible for downloading a list of github user repos
.The 'getRepos' saga fetches the data and if successful dispatches a globally scoped action LOAD_REPOS_SUCCESS by importing from 'containers/App/actions'
.The global app reducer processes LOAD_REPOS_SUCCESS and stores the repo data in the global scope
.Then in the HomePage container's index.js file, repo data is mapped to container properties using 'mapStateToProps' and a global selectRepos() selector
.The repos can then be displayed in the HomeContainer using this.props.repos
```

Why does repo data need to be stored at the global level? It doesn't seem like it's used anywhere other than the HomePage container, so shouldn't the actions, selectors, constants and reducer be scoped to the HomePage container?

Is this best practice for making data accessible across containers?

**Comment by KarandikarMihir** [comment]
> Is this best practice for making data accessible across containers?

Answers your question. 

This approach would be very useful in certain cases. If you have some data to be made globally available such as access rights to certain features of your app or current user's information, you can load it up in the global state. It all boils down to what you want to do with your data. 

The original authors of example app can shed some light on this. But IMO, the author(s) just wanted to show what _can be done_ with the data. It's perfectly alright to reuse selectors/reducers/action creators from a different container. Example app does not establish any rules simply because it's just an example! :)

**Comment by gihrig** [comment]
@KarandikarMihir Very well explained. ✨ 

@kylesavant We have an Introduction document that will be available with next release that provides a thorough overview of the boilerplate technologies and much of their operation (created by @KarandikarMihir, incidentally). You can preview this document [here](https://github.com/mxstbr/react-boilerplate/blob/dev/docs/general/introduction.md).

**Comment by RobEasthope** [comment]
@KarandikarMihir  Just read the introduction document and it's very well explained. Thank you to all those involved in putting it together

**Comment by KarandikarMihir** [comment]
@gihrig Thanks you! :smile:  @RobEasthope I'm glad I could help.. :)
