### ISSUE TITLE
Reason to use Reflect

### ISSUE THREAD

**Issue by yantakus** [mxstbr/react-boilerplate#1444]
Is there any particular reason to use
```javascript
if (Reflect.has(store.asyncReducers, name)) return
```
instead of the good old
```javascript
if (name in store.asyncReducers) return
```
here: https://github.com/mxstbr/react-boilerplate/blob/master/app/utils/asyncInjectors.js#L36 ?

I don't see any value it brings into the project. And it has several disadvantages in my opinion:
- The second one has much more intuitive syntax than the first one.
- Additional difficulties for beginners who may know about `in` and don't know about the all new `Reflect`
- The second one is not implemented in all browsers, so we have to use a polyfill and spend several bytes of bundle size for this.

**Comment by KarandikarMihir** [comment]
But we're going to need polyfill anyways, right? Might as well use `Reflect`. Correct me if I'm wrong..

**Comment by yantakus** [comment]
No, `in` operator doesn't need polyfills, it is available since javascript v 1.4 (IE5.5+, ...)

**Comment by KarandikarMihir** [comment]
No I mean, polyfill is added in `app.js` which is the root file. We're going to need it to run sagas and stuff. So why not use Reflect if we have the polyfill at our disposal? We're not importing any special polyfill to use Reflect.

Again, I'm just curious :)

**Comment by yantakus** [comment]
We can include only the ones we use as described here: https://github.com/zloirock/core-js#commonjs

This is one of recommended ways to include polyfills as described in babel docs: https://babeljs.io/docs/usage/polyfill/

**Comment by justingreenberg** [comment]
@yantakus thank you for opening this issue! as the author in this case i can provide some reasoning :) i have been using `Reflect` mainly as a functional drop in for in and delete operators—you can see it used in [some other places too](https://github.com/mxstbr/react-boilerplate/blob/fd77388ec716f9c853a2464ac4b03dfb646a3887/app/utils/tests/asyncInjectors.test.js#L61)... here's some context from [harmony-reflect](https://github.com/tvcutsem/harmony-reflect/wiki#harmony-reflect):

> In ES5, the way to detect whether an object obj defines or inherits a certain property name is to write `(name in obj)`. Similarly, to delete a property, one uses `delete obj[name]`. While dedicated syntax is nice and short, it also means you must explicitly wrap these operations in functions when you want to pass the operation around as a first-class value.
>
>With Reflect, these operations are readily defined as first-class functions: `Reflect.has(obj, name)` is the functional equivalent of `(name in obj)` and `Reflect.deleteProperty(obj, name)` is a function that does the same as `delete obj[name]`.

from discussion on original PR: https://github.com/mxstbr/react-boilerplate/pull/976#discussion-diff-78349373 

so, it's really a matter of personal preference since as you point out it is technically equivalent... i feel like the JS primitive api is so small, if someone is new to `Reflect` maybe it's not the worst thing, since it may be helpful in some other context? idk, you could totally be right

regarding the polyfill, i think that creating a custom build of `core-js` is a outside the scope of this project, and as @KarandikarMihir pointed out we currently use `babel-polyfill` to provide robust foundation, then users can further optimize if they wish. however, if you would like to put together a pull request with these changes we can continue the conversation there! i hope this helps

**Comment by yantakus** [comment]
@justingreenberg Thanks for pointing out about the functional benefits of Reflect. I never thought about it in this way. I think we can leave this as is and close the issue. Or ask other members about their thoughts on this topic if you want. For me it was a question in the first place, not a change request.
