### ISSUE TITLE
Example app uses functional instead of PureComponents

### ISSUE THREAD

**Issue by kelsonic** [mxstbr/react-boilerplate#1456]
For performance reasons it seems that using PureComponents is better optimized over functional stateless components (read [this](https://medium.com/modus-create-front-end-development/component-rendering-performance-in-react-df859b474adc#.isl0ea2hl) and  [this](http://stackoverflow.com/questions/40703675/react-functional-stateless-component-purecomponent-component-what-are-the-dif)).

Should we convert the current stateless components in the example app to PureComponents?

# Examples:
## PureComponent
```jsx
import React, { PureComponent } from 'react';

class Button extends PureComponent {
  render() {
    return <button>{this.props.label}</button>;
  }
}
```

## Functional stateless component
```jsx
function Button(props) {
  return <button>{props.label}</button>;
}
```
or
```jsx
const Button = (props) => (
  <button>{props.label}</button>
);
```

# Functional components in example app:
1. Button
1. Footer
1. Img
1. IssueIcon
1. List
1. ListItem
1. LoadingIndicator
1. Toggle
1. ToggleOption

**Comment by Necmttn** [comment]
which version of the repo you're using ? 
![image](https://cloud.githubusercontent.com/assets/5212808/21956612/c822e278-dabf-11e6-8854-b7c4c13e1014.png)
because 
```npm run generate``` does have option for create.  @kelsonic

**Comment by KarandikarMihir** [comment]
Yes, we do have an option to generate Pure components.

I'm just thinking out loud:
1. Pure components offer shallow comparison of previous and next props in `shouldComponentUpdate`. They're great if you want to avail React's life cycle methods _AND_ built-in shallow comparison. Since `Button`, `Footer`, `Img` etc. do not warrant usage of any life cycle methods, it's better to use stateless over pure. 
2. But stateless components are re-rendered every time they receive props.
3. That being said, [React team has promised](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components) optimizations for stateless components in the future.
4. Stateless components are easier to read than Pure Components.
5. But Performance > Readability.

I'd say we should convert stateless ones to pure. But let's see what others have to say about this.

**Comment by kelsonic** [comment]
@Necmttn @KarandikarMihir Sorry about the miscommunication, I had forgotten that on my version I took away the stateless component generator since I prefer using `PureComponents`.

> 5. But Performance > Readability.

Personally, I think since this is a boilerplate used specifically for production-ready apps, performance should be the main concern here.

When we use `PureComponent`s within the example app, we are demonstrating to our users that using `PureComponent`s is preferred over `stateless` components as far as performance is concerned.

If the decision is to convert them to `PureComponent`s, I'm happy to make a PR. 😄

**Comment by KarandikarMihir** [comment]
What do you think @collaborators?

**Comment by gihrig** [comment]
There is an in-depth answer to the question when to use function. Component or PureComponent on [SO](http://stackoverflow.com/questions/40703675/react-functional-stateless-component-purecomponent-component-what-are-the-dif).

In general, declaring any of them a bet practice amounts to [premature optimization](http://wiki.c2.com/?PrematureOptimization). That leaves us with using the simplest solution ([Occam's razor](https://en.wikipedia.org/wiki/Occam's_razor)).

I would prefer using function components wherever possible,  React.Component where dynamic state or life-cycle methods are needed, and React.PureComponent only where performance optimizations are proven to be needed.

Remember, in react-boilerplate we also have performance enhancements from `selectors` and `immutable` state.

**Comment by KarandikarMihir** [comment]
> Remember, in react-boilerplate we also have performance enhancements from `selectors` and `immutable` state.

Agreed. Sometimes I tend to take those things for granted. 

In addition to that, [react only updates what's necessary](https://facebook.github.io/react/docs/rendering-elements.html#react-only-updates-whats-necessary). Occam's razor ftw.
