### ISSUE TITLE
AppCache manifest error

### ISSUE THREAD

**Issue by jshultz** [mxstbr/react-boilerplate#147]
`Application Cache Error event: Manifest fetch failed (404) http://localhost:3000/classrooms`

I keep seeing that error in the console. When I look at the line number it's referencing i see

`<html lang="en" manifest="/manifest.appcache">`

However, I don't see that in the folder, but I do see manifest.json? 

Any idea what could be causing this? Is it it normal when working locally?

**Comment by mxstbr** [comment]
Are you working on the master branch or on the v3.0.0 branch?

**Comment by jshultz** [comment]
Master branch
-- 
Jason Shultz

**Comment by mxstbr** [comment]
This happens because the AppCache is auto-generated in production to cache all of the files you use. Caching during development majorly messes everything up, which is why the HTML5 file can't find a manifest - there is none.

To fix this error, remove the `manifest="/manifest.appcache"` from the index.html file during development, and add it back in before running `npm run build`. 

Also note that this was fixed and is done automatically in v3, which you can get right now by using the v3.0.0 branch!

**Comment by jshultz** [comment]
I'm starting to move all my code over from the master version to the 3.0 version of your boilerplate. it's going to take a bit of work, but it should be ok. :)

**Comment by mxstbr** [comment]
Definitely recommend doing that, it's a lot better. A few quirks to iron before the release (see the Issues list), but I can't wait!

**Comment by jshultz** [comment]
I am looking at switching it over, it just looks like a lot of code rewriting to get my actions to work again. lots of complaining about pure functions.

I have a block like this:

`componentWillMount() {
        const { dispatch, selectedTeacher } = this.props;
        this.props.dispatch(fetchClassrooms('3521'))
    }`

so that it will pull all the classrooms for a teacher when the view loads and it doesn't like it.

**Comment by mxstbr** [comment]
Yeah it's a big change, if you're deep into making your application you have to think about if it's worth the tradeoff. There's a massive amount of small fixes and a few bigger changes in v3, see #123 for more information!

----

> Note: It'd be great if you could post your code snippets as [fenced code blocks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) with three backticks, makes it much easier to read!

**Comment by Kielan** [comment]
+1 maybe worth mentioning in the README

**Comment by mxstbr** [comment]
@Kielan I'm not accepting any changes to the master branch anymore, this issue is fixed in the `v3.0.0` branch, but it'll be a bit of time until that's released.

If you want to help out and speed it up, (which would be amazing) take a look at the [issues with the "v3.0" milestone](https://github.com/mxstbr/react-boilerplate/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.0) and pick one that sounds interesting! I'll gladly help you fix the issue, ping me with any questions you have either on Github, or on [Twitter](https://twitter.com/mxstbr) or on the Reactiflux Discord Server!
