### ISSUE TITLE
Unit testing documentation is based on Jest

### ISSUE THREAD

**Issue by alexidsa** [mxstbr/react-boilerplate#1483]
[Unit test documentation](https://github.com/mxstbr/react-boilerplate/blob/master/docs/testing/unit-testing.md) says Jest is used in react-boilerplate. But when I look into the project I don't see Jest reference in packages.json and it seems like mocha+Karma are used. Is documentation outdated or am I just missing how Jest is used?

**Comment by Schubbcasten** [comment]
Jest was introduced with version 3.4 a few days ago. You are probably still using a version before that, which indeed use karma+mocha. You can go to [releases](https://github.com/mxstbr/react-boilerplate/releases) to look at the documentation of the previous versions.

**Comment by alexidsa** [comment]
You're right. I missed the latest release. Is there any upgrade strategy?

**Comment by KarandikarMihir** [comment]
@alexidsa Unfortunately, you'll have to rewrite tests. You can see [how old tests were rewritten](https://github.com/mxstbr/react-boilerplate/pull/980/files). Otherwise you can use [older versions](https://github.com/mxstbr/react-boilerplate/releases) of this boilerplate. 

Also, for a comparative analysis there's a [nice article](https://medium.com/@kentcdodds/migrating-to-jest-881f75366e7e) on medium.

**Comment by Altiano** [comment]
In changelod.md 

- **Testing setup**: Thanks to @jbinto's herculean efforts, testing is now a
  first-class citizen of this boilerplate. (the example app has _99% test coverage!_)
  Karma and enzyme take care of unit testing, while ngrok tunnels your local
  server for access from anywhere in the world – perfect for testing on different
  devices in different locations.

I think sthis should be updated?

**Comment by gihrig** [comment]
@Altiano See CHANGELOG.md line 7

> - **Switch to Jest for testing**, massive thanks to @dmitriiabramov

The passage you referenced is for an older version.

Thanks anyway for raising the issue.
