### ISSUE TITLE
Pulling in dev assets (including chunks) from a different local server?

### ISSUE THREAD

**Issue by AshCoolman** [mxstbr/react-boilerplate#1486]
Hi, after some general guidance for linking the main.js on the dev server, from a different locallly hosted app.

## Existing situation

We have an existing app we run locally (`http://big-slow-php.local`). We are adding a new react-app onto it, so what we have done in the past is just have a script tag that points to the dev webserver (`http://localhost:3000`). The chunks always try to load relatively (`http://big-slow-php.local/chunk.1.js`). 

## Previous attempts

I've tried setting `output.publicPath` to the absolute path (`http://localhost:3000`), but it continued to pull chunks relatively.

I've also tried disabling chunks, by removing the CommonChunking plugin in `webpack.prod.babel.js` - but there was still `1.js`, `2.js` etc created (and relatively hosted).

In the end, I did a production build, generated a file-list.txt. The php app grabs the file-list.txt, and reads in all the assets and hosts them itself. Which is slow, and doesn't have the HMR goodness.

## Question

Am I on the right track? 
Am I missing something simple?

Any help would be great :)

Thanks!

**Comment by jeremyadavis** [comment]
Although I'm not great at webpack (which is why I chose this boilerplate because the creators are), here's the modifications I had to make to get my app running inside an enterprise portlet server, maybe they can be of help to you.

You might need to paste your webpack files in so I can better understand a few things, but here's my recommendations.

First off, I don't believe setting [publicPath](https://webpack.github.io/docs/configuration.html#output-publicpath) will have any real effect on your files when running off of the dev server. It kicks in on a production build. 

I've disabled the OfflinePlugin for my setup, because I had too many issues with it early on and had plans of circling back to solving them, but never did.

You might need to use the \_\_webpack_public_path\_\_ variable so that you can dynamically set the path at runtime. For me, I don't know what my absolute path is until WebSphere tells me, so I modified my prod webpack as follows:
``` javascript
// webpack.prod.babel.js
...
entry: [
    path.join(process.cwd(), 'app/entry.js'),
    path.join(process.cwd(), 'app/app.js'),
  ],
...
```
 
and the job of entry.js is to get the dynamically set absolute path like so,
``` javascript
// entry.js
...
const script = document.querySelector('meta[name="app-root"]');
__webpack_public_path__ = script ? script.getAttribute('content') : '/'; // eslint-disable-line
...
```

From there my chunks load correctly.

**Comment by AshCoolman** [comment]
Yes, that seems to have been the correct approach. Thanks.

Also helpful: https://github.com/webpack/webpack/issues/2776#issuecomment-233208623
