### ISSUE TITLE
node: not found

### ISSUE THREAD

**Issue by DQvsRA** [mxstbr/react-boilerplate#1507]
I have a problem while "npm run setup"

![screenshot from 2017-01-22 12 31 59](https://cloud.githubusercontent.com/assets/442111/22182183/39451784-e09f-11e6-89b4-5480f8715855.png)

**Comment by DQvsRA** [comment]
After installing node-legacy with "sudo apt install nodejs-legacy" i have this error while running "npm tun setup"

![screenshot from 2017-01-22 12 43 16](https://cloud.githubusercontent.com/assets/442111/22182225/60cb7dc4-e0a0-11e6-9842-af5f8eb63870.png)

**Comment by MattKetmo** [comment]
The setup script requires node >= 5 https://github.com/mxstbr/react-boilerplate/blob/fd77388ec716f9c853a2464ac4b03dfb646a3887/internals/scripts/setup.js#L59

On some Linux distro (eg. debian/ubuntu) most recent version of node are installed as `nodejs` executable instead of `node`. Best thing is to alias it, eg. 
```
sudo ln -s $(which nodejs) /usr/local/bin/node
```

**Comment by gihrig** [comment]
> On some Linux distro (eg. debian/ubuntu) most recent version of node are installed as nodejs

WTF? Why would they do that?!

In any case, thanks @MattKetmo for the tip!
