### ISSUE TITLE
Autobinding instead of binding in the constructor

### ISSUE THREAD

**Issue by nikgraf** [mxstbr/react-boilerplate#158]
See https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

Prebinding in the constructor:

```
class Counter extends React.Component {
  constructor() {
    super();
    this.tick = this.tick.bind(this);
  }
  tick() {
    ...
  }
  ...
}
```

Syntactical sugar:

```
class Counter extends React.Component {
  tick = () => {
    ...
  }
  ...
}
```

**Comment by mxstbr** [comment]
Oooh I didn't know about that, much nicer! Would love a PR for this.

**Comment by jbinto** [comment]
FWIW, I think it's worth pointing out that this isn't an ES6 feature, it is a stage 1 proposal that has [support only in Babel](https://github.com/babel/babel/blame/master/packages/babel-plugin-transform-class-properties/src/index.js).

https://github.com/jeffmo/es-class-fields-and-static-properties

I don't have a problem with using experimental syntax but I definitely think it's worth documenting anything like this, since it could change on a whim. Docs should make it clear the project relies on experimental language features, which ones, and why.

**Comment by mxstbr** [comment]
:+1: Thanks for the notice, I hope I don't forget to document it!

**Comment by jbinto** [comment]
I opened #165 to track it.

**Comment by mxstbr** [comment]
Thanks @jbinto, closing this issue!
