### ISSUE TITLE
Bug: npm run pagespeed on V3.0.0 branch may need authentication?

### ISSUE THREAD

**Issue by paul42** [mxstbr/react-boilerplate#177]
I'm not certain if this is desired behavior:
ERROR
Error: {"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"Only paid plans may bind custom subdomains.\nFailed to bind the custom subdomain '0bfa42b5-ddd8-489d-93fb-d031b06ed7aa' for an unauthenticated client.\nSign up at: https://ngrok.com/signup\n\nIf you have already signed up, make sure your authtoken is installed.\nYour authtoken is available on your dashboard: https://dashboard.ngrok.com\n\nERR_NGROK_305\n"}

**Comment by mxstbr** [comment]
@paul42 good catch, that shouldn't happen - would you mind researching why this doesn't work anymore?

**Comment by paul42** [comment]
Sure, do you know if it worked on a previous branch?

**Comment by mxstbr** [comment]
It definitely worked on v3 a few weeks ago, not sure why it doesn't anymore.

**Comment by mxstbr** [comment]
Got it!

The problem is that since v0.2 to use ngrok you need to have an account. (highly likely to battle abuse, see [here](https://inconshreveable.com/05-29-2014/automate-away-your-problems-combatting-illegal-abuses-of-ngrok/) /cc @inconshreveable)
Back when @callumlocke did the [mass dependency upgrade](https://github.com/mxstbr/react-boilerplate/commit/5b595fbab1fac6a56f6bc3c90307abb77754213b) (thanks again!) he also update ngrok from v0.1 to v0.2, which slipped under my radar. This broke both the `npm run serve` as well as the `npm run pagespeed` command.

I've reverted this change and fixed the problem in 40a230f, pull the newest version and `npm install` to have the two commands working again!
