### ISSUE TITLE
Linting errors should not give npm errors

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/react-boilerplate#186]
At least in v3.0.0 when you lint and get an error, it spits out a npm errors, which not only are ugly but push the actual linter errors away from the user.

Here's an example:

<img width="1680" alt="screen shot 2016-02-21 at 8 23 24 pm" src="https://cloud.githubusercontent.com/assets/8217766/13207173/4f1cce5e-d8d9-11e5-8459-74112e155a6d.png">

 I have to scroll up to see the actual error:

<img width="1680" alt="screen shot 2016-02-21 at 8 23 43 pm" src="https://cloud.githubusercontent.com/assets/8217766/13207175/5138bc20-d8d9-11e5-9aa7-3105f5426ac3.png">

Opinionated linters like standard or xo show nice errors, so they might be a good place to look.

**Comment by mxstbr** [comment]
The linting scripts have to exit with a non-0 status, so that Travis CI fails the build if the linting doesn't go through.

I'm pretty sure there's no way to exit a npm script with a non-0 status without showing these errors – if you find one, I'd love to see how that'd work while still failing on travis!
