### ISSUE TITLE
3.0.0 Remove a generated resource

### ISSUE THREAD

**Issue by mariusleu** [mxstbr/react-boilerplate#281]
Using `npm run generate <resource>` to generate components, containers, routes etc. is a  very great and welcome feature.

But how can we remove a generated resource after we generate it? Maybe we generate it misspelled or things like this.

**Comment by Kuzmin** [comment]
Most resources are isolated to their own directory, so you should be able to just delete them with `rm`. If you're using Git it's also possible to reset to `HEAD` which will have the side effect of deleting all code changes since the last commit. 

I think these two should be able to provide you with what you need, since the tool used by `npm run generate`, (https://github.com/amwmedia/plop)[plop], doesn't support undo.

**Comment by mxstbr** [comment]
Exactly what @Kuzmin said, thanks!
