### ISSUE TITLE
Question: How to provide a second root HTML file?

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#289]
Redarding v3,0.0: 
I need to provide a second root HTML file (besides index.html) to allow for OpenID-Connect token refresh callbacks. The configuration of webpack in this boilerplate is very delicate and I don't want to accidentally break the build process so I'm asking here for help.

The callback file is basically just a blank HTML file with an associated script which is executed on load. The script needs access to the node modules. The file needs to be called `refresh.html`.

I've tried using the `!file` import at `app.js` but this doesn't work with JavaScript inside html `<script>` tags.

I've then tried to write a new module in a folder besides `app` called `refresh` and in it included the script in a file called `index.js`. Then I've modified `webpack.base.babel.js` entry options to look like this:

    entry: {
        app: options.entry,
        refresh: './refresh/',
    }

The script now gets executed correctly when the callback is triggered within the app, but not bundled within a separate HTML file. There is no HTML file being generated. Do you know what I'm missing here?

**Comment by mxstbr** [comment]
*We generally recommend posting questions like this about the usage of the boilerplate to our [gitter](https://gitter.im/mxstbr/react-boilerplate) so the issue tracker stays clean!*

`'file!refresh.html` should work fine, the reason the script isn't included is because it isn't run through [`HtmlWebpackPlugin`](https://github.com/ampedandwired/html-webpack-plugin), which takes care of that.
I've never done this, but I think the way to go here would be to statically reference the script you want in your HTML file, load it with the file loader as above and then it should work.

Also pinging @jantimon, who's the HtmlWebpackPlugin maintainer, maybe he has a better idea on how to solve this use case!

**Comment by maxmantz** [comment]
OK moving this to gitter.
