### ISSUE TITLE
Discuss: Webpack DLL / DLLUser plugins for long term caching?

### ISSUE THREAD

**Issue by ryan-roemer** [mxstbr/react-boilerplate#319]
Nice boilerplate!

Looking at https://github.com/mxstbr/react-boilerplate/issues/127, we were just chatting this at work, and I posted a comment on @okonet 's blog post, but I'm curious if there was a consideration of the DLL plugins which are part of core and have a similar manifest scheme?

* https://webpack.github.io/docs/list-of-plugins.html#dllplugin ([example](https://github.com/webpack/webpack/tree/master/examples/dll))
* https://webpack.github.io/docs/list-of-plugins.html#dllreferenceplugin ([example](https://github.com/webpack/webpack/tree/master/examples/dll-user))

The nice thing about DLL plugin is if you have completely separate builds (say 10 different app repos), they can all consume the same DLL-generated plugin.

**Comment by ryan-roemer** [comment]
I've written a basic run down of how DLL/DLLUser plugins work for a niche project https://github.com/FormidableLabs/requirepack/blob/master/docs/shared-libraries.md

**Comment by okonet** [comment]
Hey @ryan-roemer 

I've answered here https://medium.com/@ryan_roemer/hi-andrey-681e309bfc62#.u6pznvdo3

Not sure why, but I didn't get any notifications from medium.

Shortly, I have no idea how this one works, so need to check it out firstly. But I assume it didn't exist back when.

**Comment by datapimp** [comment]
Would you accept a PR if I implemented it for you? It is a pretty simple addition with just very little documentation or writing about it, but one of those things that once you use it it is hard to go back.

It will result in significant reductions in build time, and since it is going to be bundling files that will likely never change in between releases of the boilerplate, there is little downside to using it.

Basically the idea is that webpack caches the context with all of the module ids, paths, chunks, etc and writes it to a JSON manifest, which it will export to disk.  This is the DLL.  The boilerplate project would do this every time you release a new version and the dependency versions have changed.  You could also do this in a postinstall step for the boilerplate, so that it happens locally on the developer's machine one time.

For every day development usage in your project, you will have the DLL Reference plugin which points to this manifest.  This saves the development project a ton of work that it never really needs to do anyway since react, redux, react-router, etc etc should always be the same when installed from npm.

**Comment by mxstbr** [comment]
Yes, sounds awesome! We'd want to put that ace explanation into the docs to and add comments, but please submit a PR!

**Comment by datapimp** [comment]
I wanted to build a real app with the boilerplate first before attempting this, and it took a little longer -- mostly because I ended up exploring the sagas / reselect / immutable stuff since my first instinct was to remove those and then I became more and more sold on them.  

Adding / removing dependencies like that is something that would be a common step for most consumers of the project, and that will have some impact on the DLL configuration.  I think I have a good idea for how to tackle this and will hopefully get a chance to do this later in the week.

**Comment by mxstbr** [comment]
Awesome @datapimp, can't wait!

**Comment by joevbruno** [comment]
@datapimp the DLL plugin really makes a difference in incremental built times, especially if you are using a third party library of components like React-Toolbox or Material UI. At work, when we introduced the plugin, our hot-reloading build times fell from 5 seconds to .3 -1.2 seconds. We found that you want to include as many of your third-party dependencies as possible, but it is sometimes deceptive as to what these are. For instance, if you use babel-polyfill, you are by extension using core-js. We did not have core-js listed in our package.json, but including it in the list of vendors for the DLL plugin made a decent difference (like 1.5 seconds shaved off). We also found it helpful to include a number of the redux-dev dependencies, hot-middleware, and other dev-only dependencies. Using the webpack analyzer is really helpful to see what is actually in your bundle, and therefore, what you could potentially delegate.

**Comment by datapimp** [comment]
@joevbruno that is a good tip.  I submitted a PR that has a working example of the DLL Plugin, and it seems to speed things up  -- average `6000ms` before DLL, `3800ms`  average after .  Still need to make some tweaks, cleanup, and document.   Feedback welcome

**Comment by mxstbr** [comment]
Done by the amazing @datapimp in #495! :tada:
