### ISSUE TITLE
Livereload breaks after running clean script

### ISSUE THREAD

**Issue by Aweary** [mxstbr/react-boilerplate#355]
### Steps to Reproduce

1. `git clone https://github.com/mxstbr/react-boilerplate.git && cd react-boilerplate`
2. `npm install`
3. `npm run clean`
4. `npm start`
5. Open editor and browser
6. Make a change (e.g., change "This is a Homepage!" to "Testing")

### Expected results

The view in the browser updates with the new value

### Actual results

The browser does not update until you manually refresh

### Details
* Livereload does work before running `npm run clean`
* Using node `5.3.0`

**Comment by mxstbr** [comment]
That's because stateless components are currently not hot reloadable, and after running `npm run clean` all components are stateless ones.

Nothing we can currently fix I'm afraid, but you can change that on your side by changing the component you want to hot reload to `class` or `createClass` notation! :+1:

**Comment by Aweary** [comment]
Maybe the root component shouldn't be a SFC after running `npm run clean` if it breaks this?

**Comment by mxstbr** [comment]
The problem is that if we don't do that, the linter complains because those components _should_ be stateless. Then we'll get issues saying "After `npm run clean` linting doesn't work" 😕

Maybe that's preferable though, now that I think about it like that. Would you mind adjusting the templates in `internals/templates` and submitting a PR?

**Comment by Aweary** [comment]
Yeah I think a linting warning is better than breaking a major feature. Ultimately this should be resolved by https://github.com/gaearon/react-hot-loader/pull/240 (I believe), but until then adjusting the templates seems to be a smart move. I can definitely get a PR going.

Can you reopen this issues so I can reference/close it from the PR?

**Comment by mxstbr** [comment]
Yeah, can't wait to finally land that! Have reopened.
