### ISSUE TITLE
webpack config resolve.packageMains purpose

### ISSUE THREAD

**Issue by Moeriki** [mxstbr/react-boilerplate#402]
In the process of integrating react-storybook into my react-boilerplate based project I had some issues making it work with a specific webpack config.

react-storybook allows you to provide your own webpack config, in case you need specific loaders / resolve config. A certain config in the react-boilerplate resolve broke the react-storybook build.

```
> resolve.packageMains

Check these fields in the package.json for suitable files.
```

The webpack config isn't very clear in explaining it. When removing it, my app still seems to work fine. What exactly is it used for and can I safely remove it?

**Comment by mxstbr** [comment]
It makes imports nicer by setting the `app` directory as a default resolve. I.e. instead of doing

```JS
import Button from '../../components/Button';
```

You can do 

```JS
import Button from 'components/Button';
```

And webpack will automatically check that the file exists in the `app/` directory before going to the `node_modules` folder. Much nicer imports! :+1: 

*(See the [documentation about this feature](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories))*

**Comment by mxstbr** [comment]
Please note that we're using webpack 2, so some things might be different from the way the `react-storybook` documentation tells you!

**Comment by inyigo** [comment]
@mxstbr  have you managed to make storybook work?

**Comment by marc-rutkowski** [comment]
Just wrote a little post about this topic.
https://medium.com/@mrutkowski/react-storybook-with-react-boilerplate-b95f541f5f7c#.3oodfi3vj
