### ISSUE TITLE
Tests failing to run

### ISSUE THREAD

**Issue by maxmantz** [mxstbr/react-boilerplate#418]
For a reason unknown to me, from one day to the next my tests stopped working. The strange thing is that I haven't changed any configs before this error occurred. The following error is thrown:

> 30 05 2016 10:16:45.468:WARN [preprocess]: Can not load "webpack"!
> Error: Passed 'options' object don't look like a valid webpack configuration
>  Uncaught ReferenceError: require is not defined
  at C:/Projekte/react-boilerplate/internals/testing/test-bundler.js:3

This is my  [karma.conf.js](https://github.com/mxstbr/react-boilerplate/files/289157/karma.txt) & [webpack config](https://github.com/mxstbr/react-boilerplate/files/289171/test-config.txt)
with the `test-bundler.js`:

```
// needed for regenerator-runtime
// (ES7 generator support is required by redux-saga)
import 'babel-polyfill';

import sinon from 'sinon';
import chai from 'chai';
import chaiEnzyme from 'chai-enzyme';

chai.use(chaiEnzyme());

global.chai = chai;
global.sinon = sinon;
global.expect = chai.expect;
global.should = chai.should();

// Include all .js files under `app`, except app.js, reducers.js, routes.js and
// store.js. This is for isparta code coverage
const context = require.context('../../app', true, /^^((?!(app|reducers|routes|store)).)*\.js$/);
context.keys().forEach(context);
```

Any ideas what causes this? Why is `require` not defined?

**Comment by maxmantz** [comment]
@mxstbr I know this might be hard to analyse from afar, but I really need your help here. I don't know what caused this error in the first place - I haven't changed anything in the configuration, yet from one day to the next my tests threw these errors.

In addition, I've also mentioned before that I think the usage of `test-bundler.js` has severe limitations on how the tests can be run. For example I've tried the [rewire](https://github.com/speedskater/babel-plugin-rewire) plugin to mock module dependencies, and it doesn't work because every tests gets loaded through this line:
`require.context('../../app', true, /^^((?!(app|reducers|routes|store)).)*\.js$/);`
which somehow blocks external plugins like these from working. I understand that this is required for code coverage to work, but could it be possible to make a separate test config for coverage, while still enabling us to use plugins like these?

**Comment by Kielan** [comment]
@maxmantz I think though I'm not 100% sure that there is a bug in babel webpack a few days ago that is being worked on

**Comment by maxmantz** [comment]
I don't think so. I use the plugin in other projects and it works just fine.

**Comment by maxmantz** [comment]
I'm currently working on a test setup using just mocha and chai (without karma & test-bundler). Hoping this will fix the issue. I will post updates here once I got it working.

**Comment by mxstbr** [comment]
We switched to using the test bundler because mocha require hooks (`mocha --require js:babel-core/register`) don't allow for a bunch of custom, webpack specific stuff. E.g. with webpack you can import images, but if you do that the tests won't run which is really annoying.

The idea is to have a webpack compiled build that's testable, which is what the `test-bundler` achieves. This means that we're using our standard setup which in turn means that whatever works in our apps works in our tests.

If you have any better ideas of how to do this feel free to submit a PR, I have yet to figure out a better solution! (the current one was thought up by the amazing @jbinto)

---- 

To answer to the question at hand, I've sadly never seen that error before, so I can't really help you with it! :confused: Since it seems like an environmental problem on your end, I'll close this issue for now—feel free to comment again if you think this is something we can fix from our side!

I hope you'll figure it out soon…

**Comment by tomascharad** [comment]
This same thing happened to me, but I'm trying to run webpack from sails with sails-webpack and importing and exporting de config from webpack.dev.babel.js, so it is probably an environment problem in my case.

**Comment by tomascharad** [comment]
Solved by using:

```
var webpack = require('./../webClient/internals/webpack/webpack.dev.babel.js');
module.exports.webpack = {options: webpack};
```

**Comment by Peleg** [comment]
What version of `karma-webpack` are you using?

I was getting the same error on `1.7.0`. Upgrading to `1.8.0` solved the problem.
