### ISSUE TITLE
service workers integration

### ISSUE THREAD

**Issue by fortm** [mxstbr/react-boilerplate#439]
thanks for wonderful react boilerplate 👍 

I think this is using service workers as in description. Does this means it qualifies for progressive web app reactjs architectures if we start with it? Or we will need to include ourselves libraries like : **sw-precache** and **sw-toolbox**

**Comment by tsm91** [comment]
No it has nothing to do with progressive webapps, all it does is using [offline-plugin](https://www.npmjs.com/package/offline-plugin). Which caches you static assets with service workers.

So it is very far away form what is presented here for example [Instant Loading: Building offline-first Progressive Web Apps - Google I/O 2016](https://www.youtube.com/watch?v=cmGr0RszHc8).

**Comment by mxstbr** [comment]
Thanks to @tsm91 for the great answer, let me elaborate a bit:

I'd love to include more helpful libraries to make progressive web apps with this boilerplate easier, but it's hard since they are very much specific to your exact app. Every PWA solution has to be tailored to the app at hand.

The `offline-plugin` is a great general-purpose solution for most apps, for more you'll have to dig in yourself! If you have any other ideas for general tools we should include, please let us know!
