### ISSUE TITLE
Global Configuration Variables

### ISSUE THREAD

**Issue by peterpuzos** [mxstbr/react-boilerplate#446]
This is by far the best React / Redux boilerplate out there.  All the best practices in one place, it's fantastic!

I have a quick question about Global config variables (i.e. api urls).  Where do you suggest we define them?  Should they go in Package.json along with all the eslint stuff?

**Comment by maxmantz** [comment]
Suppose you have the following `config.json` file:
```
{
 "apiRoot": "http://myApiRoot.com"
}
```
External config files can be added to your `webpack.base.babel.js` file like this:




```
  externals: {
    config: JSON.stringify(require('path/to/config.json')), //eslint-disable-line
  },
```

Then in your code you can use it like this:

```
ìmport config from 'config';

console.log(config.apiRoot);
```

Hope this helps.

**Comment by mxstbr** [comment]
Exactly what @maxmantz said, thanks for answering!

**Comment by karloespiritu** [comment]
Is there a way to declare the API URL a variable, such as using environment variables? In the example above, I have to declare the API URL statically, which means if deployed to a different server environment (staging, production, etc.), I have to update the API URL manually.

**Comment by izziaraffaele** [comment]
This does not work in test environment as the `webpack.test.babel.js` configuration file does not inherit from `webpack.base.babel.js`.

Additionally, I'm getting an error `Unable to resolve path to module 'config'` and so, the solution of @mxstbr  does not work for me at all.

**Comment by shawnmclean** [comment]
How can this work in a situation where we're building once and deploying to multiple environments?

**Comment by vlobrigo** [comment]
i think i have the same issue, I want to create a config file for google API, data include the secret keys, etc.. how will I add it up in the boilerplate? and how will I access the list of secret keys from the config. thanks

**Comment by gihrig** [comment]
@shawnmclean @vlobrigo @karloespiritu  For multiple environments, 

 - The config file resides in a secure location outside your app.
 - The path (absolute or relative) from your app to the config file is the same for all environments
 - Each config file is has settings appropriate to that environment.

How you access that file from within your app via `webpac externals` or webpack `DefinePlugin`, you will have to work that out for your environments.

**Comment by FaustoC** [comment]
How can i achive an external config.json (not bundled so sysadmins can work on it) that get included runtime and isn't statically bundled?

**Comment by rsteckler** [comment]
Couple of options, none of which are amazing:
1)  Build on the prod server.  This lets you pick up the environment variables during the build and bundle them into the app.  The challenge here is that if you have multiple prod servers and the build runs on them individually, you end up with servers that contain different builds with different file names from the uglification process.  (e.g. main.123.js and main.456.js).  This breaks when you're load balancing the servers because you get the HTML from one server and the JS from the other, resulting in a 404 on the js file.
2)  Get them from the server at runtime.  You can make a call to the server whenever app.js loads, but that hardly seems efficient.
3)  Bundle the variables at build time on the build server.  This is what I settled on.  It's not "runtime" but at least I have a central secure place I can change the values.

None of those are awesome solutions, but it's all I can come up with.

**Comment by shawnmclean** [comment]
The solution we settled on is to deploy an external config file that is loaded in when the app is started. This causes a slight delay for the app to start. 

Our CI process is: 

  1. Build & Unit test on build server with `NODE_ENV=production`. (it seems anything else and react complains)
  2. Packaging copies a `config.json` file to dist directory.
  3. Deploy tool updates this `config.json` as per environment.
  4. Deploys the dist directory.
