### ISSUE TITLE
Is the webpack config compatible with Windows?

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#45]
Somebody [asked me on Hacker News](https://news.ycombinator.com/item?id=10796735) if the webpack config is compatible with Windows – any Windows users who have tried and for whom it worked/didn't work?

**Comment by lwouis** [comment]
I tried on my windows 10 machine. It's indeed not working. The issue lies with the `scripts` section of the `package.json`. There, `start` and `serve` break since it's not cross-platform. I get the following error:

`'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.`

I also got the following warning during `npm install`:

`npm WARN install Couldn't install optional dependency: Unsupported`

**Comment by mxstbr** [comment]
@lwouis thanks so much for trying, any ideas on how to set the NODE_ENV in a cross-OS compatible way?

**Comment by lwouis** [comment]
Yes, see my updated comment. Very easy fix actually :)

**Comment by zavelevsky** [comment]
From what I remember - it's always an issue with setting the environment variables.
I wasn't aware of 'cross-env' so I solved it differently.
I added a script called 'win' that calls webpack without setting any environment variables and I created a batch file for Windows that calls SET in order to set the desired environment variable and then calls `npm run win`.

**Comment by mxstbr** [comment]
Did it with `cross-env`, as it worked for @lwouis. Fixed on master now, thanks so much for the help!

**Comment by Devanathan** [comment]
@Iwouis, thanks for your comment on fix for NODE_ENV in Windows - works great now!
