### ISSUE TITLE
Why not use providePlugins to add React in Webpack?

### ISSUE THREAD

**Issue by jupitercow** [mxstbr/react-boilerplate#531]
Just curious. It seems like we might as well streamline the modules and make React available to all templates and not have to have it in the import block. I mean the generators add it automatically, so it isn't a big deal... Mostly I figure there was a decision against it, because this thing is so well thought out. So curious if there was a reason.

```
new webpack.ProvidePlugin({
      // make fetch available
      fetch: 'exports?self.fetch!whatwg-fetch',
      React: 'react',
});
```

I love this boilerplate so far. Thanks!

**Comment by mxstbr** [comment]
With tree shaking, you might be getting rid of parts of React that you're not using! (especially if you're using imports like `import { Component, createComponent } from 'react'`) Admittedly, this isn't yet really happening due to the way React is built currently, but the team is aware of it and working towards a better way of doing things afaik.

You've also tightly coupled your components to your environment – sharing those components will be basically impossible and/or require a very diligent environment setup for the user.

This is why we don't do it generally in the boilerplate. That being said, if you're working on a side project on your own please go ahead and prefer it that way go ahead! _Nobody_ is going to keep you from doing it :grin:

**Comment by jupitercow** [comment]
Thanks. Shareable components was exactly what I was looking for. A very good reason not to do it.
