### ISSUE TITLE
How to run a saga for a container that does not use react-router ?

### ISSUE THREAD

**Issue by rcholic** [mxstbr/react-boilerplate#537]
I am a bit stuck in plugging in a `saga` that was required for a container component that does *NOT* need react-router. It seems to me that the saga for a container that uses react-router is taken care of automatically in this react-boilerplate code, because I don't need to do anything other than run the built-in `generator` for a router.

I find the following code in `store.js`:
```
  store.runSaga = sagaMiddleware.run;
```
and I tried to run my custom saga this way, but it does not work:
```
store.runSaga = sagaMiddleware.run(mySaga); // note: mySaga
```

Could someone help me understand how to plugin a saga to the store for a container component that does not require react-router?

**Comment by mxstbr** [comment]
You were close, but **changing the `store.runSaga` reference will break all other sagas**, since they call `store.runSaga` to point to `sagaMiddleware.run`.

Can you try adding that line above the assignment? That _should_ work!

```JS
sagaMiddleware.run(yourSaga);
store.runSaga = sagaMiddleware.run;
```

**Comment by Augustin82** [comment]
I came here this morning to ask the same question. Last week I've been struggling a bit with the following structure:
- I have a "routed" HomePage that includes several containers
- each container will independently run their own sagas (like, one container is an Alerts list that will handle the display, closing, etc., of alerts while the other container is an Items list that will also handle display, ordering, etc. of items)

I am not sure how to do that, and sure wouldn't mind a piece of doc explaining how to "plug in" the relevant saga files.

Full disclosure: I'm a React/Redux newb and am relying heavily on this most magnificent boilerplate to help me put into action the stuff I've learnt about those technos. Some technical-magical things you do in the boilerplate is a bit confusing sometimes (the automatic injection in app.js for example) and it would definitely help people like me if there was some doc explaining why the magic is done and what it is exactly that it saves me from having to do.

**Comment by mxstbr** [comment]
Yeah, I think having that doc sounds good – just need somebody to get around to actually writing it. :wink:

Since the question seems to be answered, I'll close this issue for now – feel free to continue discussing though!

**Comment by timothyallan** [comment]
Having the "nested" container have its Saga's loaded by it's parent container couples it to the parent though, no?

To take @Augustin82's example, you can't just throw in a ```<AlertsList />``` component anywhere, unless you first go adn explicitly put a reference to it's Saga(s) in the parent container. Likewise, you've now also got to remember to remove the Alerts Sagas from the parent container if you remove the Alert component from the parent container.

Not the end of the world by any means, but definitely something that could bite you given a large enough project.

**Comment by mxstbr** [comment]
Yeah, you could also create a global `saga.js` file that re-exports all of them, but it's not optimal – there isn't really a better way to do it that I can think of.

**Comment by garajo** [comment]
I want to run a saga in the container/App level, and I landed on this question thread, which at first seemed to solve my problem. But the saga never gets invoked. I created a `container/App/saga.js` file and hook it up as mentioned above `sagaMiddleware.run(yourSaga);`. I've verified the saga gets included. But when I try to dispatch an action from `App/index.js`, and though the state does get changed in redux, the listening saga doesn't seem to 'hear' the dispatch. Is this the correct way to go about this? My motivation is that I want a saga that is globally triggered once, regardless of the route the user lands on.

**Comment by tayyabshabab** [comment]
@garajo I ran into this same issue today. And I fixed it by removing below code from the generator function in sagas.js as it suspends its execution. Hope it helps you also.

// Suspend execution until location changes
yield take(LOCATION_CHANGE);
yield cancel(watcher);

**Comment by bobkocisko** [comment]
I think there's a slightly more elegant way to do global sagas, though not different in principle than some of the answers already mentioned here.  I thought I'd mention my approach in case anyone finds it helpful.

**app/store.js**, at the end of the `import` statements
```javascript
// ...
import { getAsyncInjectors } from 'utils/asyncInjectors';

// Global sagas
import yourSagas from 'containers/YourContainer/sagas';
import yourOtherSagas from 'containers/YourOtherContainer/sagas';
// ...
```

**app/store.js**, right after the `store.runSaga = sagaMiddleware.run;` line
```javascript
// Run any global sagas
const { injectSagas } = getAsyncInjectors(store);
  
injectSagas(yourSagas);
injectSagas(yourOtherSagas);
```

This allows you to define sagas as you normally would, exporting an array as the output of your sagas.js file and this automatically runs all the sagas in the array.

**Comment by learntoswim** [comment]
@bobkocisko I like your approach.

I hacked together my solution, as follows:

**app/sagas.js**
```javascript
// Export all your sagas here so the sagaMiddleware imports them
import { getUserAuthenticated } from './containers/App/sagas';
export default [
  getUserAuthenticated,
];
```

**app/store.js**
```javascript
// Import global sagas
import globalSagas from './sagas';
```

Then inside `export default function configureStore(initialState = {}, history){`

```javascript
// Run Global Saga automatically
sagaMiddleware.run(...globalSagas);

// Extensions
store.runSaga = sagaMiddleware.run;// (...globalSagas);
```

**Comment by bobkocisko** [comment]
Thanks @learntoswim.  Can sagaMiddleware.run accept multiple sagas?  I was under the impression that it could only run one at a time.

**Comment by learntoswim** [comment]
@bobkocisko Good question, I [believe they can run more](https://github.com/yelouafi/redux-saga).

I prefer your solution much better, anyway. I was merely offering some other opinion for others.

**Comment by bobkocisko** [comment]
Ok sure.  In the example you linked it is running only one saga (one generator function).  Also, when I tried to pass an array to the `run()` method it threw an error.

**Comment by learntoswim** [comment]
@bobkocisko I never tried!

**Comment by dstuecken** [comment]
I stumbled across this thread since was figuring out how to implement global sagas as well, now that i tried your suggestions here i am asking myself were i should put the reducer for my global saga? How did you guys do that?

**Comment by mxstbr** [comment]
> Is it sufficient to just put it in the createReducer() object in the main reducers.js?

Yes!

**Comment by bobkocisko** [comment]
@dstuecken, great question!  I thought of updating [my comment](https://github.com/mxstbr/react-boilerplate/issues/537#issuecomment-235065705) when I ran into a saga needing a companion reducer but it turned out that my solution seemed a bit too complex for a simple response.  Basically rather than [what I initially suggested](https://github.com/mxstbr/react-boilerplate/issues/537#issuecomment-235065705), I decided to maintain consistency with `routes.js` by using `Promise.all(...)`, `System.import(...)`, `injectReducer(...)` and `injectSagas(...)` to load both the sagas and their reducers.  Actually to be honest I haven't needed to load more than one saga/reducer pair yet but I wanted a solution that would support more saga/reducer pairs in the future.

However while I was happy with this approach (and still use it now), it caused additional complexity in two ways:

1.  `configureStore(...)` could no longer be synchronous since the main `App` component relied on the presence of the global reducer.  When `configureStore(...)` was synchronous and the global reducer was loaded asynchronously, it caused an error because the reducer was not loaded yet when the `App` component needed it.  To fix this, I decided to change `configureStore(...)` such that it returns a Promise which is only resolved when the saga/reducer pair is fully downloaded and injected.  But then of course the `configureStore(...)` callee in `app.js` had to be changed downstream and the `configureStore(...)` tests had to be adjusted as well to properly deal with this change.

2. I also found that the hot module reloading section of `configureStore(...)` was failing about 50% of the time and throwing a fatal error at runtime.  Which was not acceptable of course.  So I decided to introduce a Promise chain inside of `configureStore(...)` which would make sure that the hot reloading section completes, and also the loading of the global sagas and reducers completes, before `configureStore(...)` returns.  This change restored the robustness of the app.

As a side note, my personal opinion is that `configureStore(...)` should return a Promise anyway because of the hot module reloading code inside of it.  It seems that as it currently is written in the base code, it is a race condition already.  If you get any surprising situations where the app completely fails to load a throws a fatal error about HMR, be suspicious of this chunk of code.

As you can see, my code changes were substantial enough to be difficult to merge into the previous comment.  I'm not sure how universal or correct my approach is, but it is working great for now.

I would say that your best bet with this is to (unfortunately) dive into `configureStore(...)` and its surroundings in `app.js`, understand it deeply and then decide how exactly you want to diverge from the base for your needs.  Good luck and Godspeed!

**Comment by mxstbr** [comment]
> It seems that as it currently is written in the base code, it is a race condition already. If you get any surprising situations where the app completely fails to load a throws a fatal error about HMR, be suspicious of this chunk of code.

Could you elaborate on this? What would you do differently? We should really really fix this if there's a that grave bug in there.

**Comment by dstuecken** [comment]
I tried your suggestions but somehow my saga is not executing after dispatching the action.
It is like my registered saga is overwritten somewhere since i see that the take() function is called but it is not responding to my action dispatch. Do you think it may has something to do with the HMR?

**Comment by bobkocisko** [comment]
@dstuecken, I reviewed my code this morning to see if I forgot anything.  I see that `configureStore(...)` doesn't actually load the saga/reducer pair but rather `app.js` does that in a `then(...)` clause after calling `configureStore(...)`.  Also, I see that in the Promise chain inside of `configureStore(...)`, the last `then(...)` clause (after the HMR section) is this:

```javascript
  .then((store) => {
    // Initialize it with no other reducers or sagas
    store.asyncReducers = {}; // eslint-disable-line no-param-reassign
    store.asyncSagas = {}; // eslint-disable-line no-param-reassign
    return store;
  });
```

Finally, I should mention that I am working off an older version of `react-boilerplate`.  I cloned from https://github.com/mxstbr/react-boilerplate/commit/7c5d57ba277a286744b31ee0ae8be31c85c44d50.  I see that there have been changes since then to `app.js` including some global saga/reducer stuff so I can't guarantee that my suggestions are still completely valid.

**Comment by dstuecken** [comment]
Hmm i don't have any Promise chains inside my configureStore() at all. Could you give me a full example of your global saga initialization in app.js?

**Comment by AshCoolman** [comment]
Newbie to this project, but I'll share my "freshie" POV. It surprised me that the default pattern expressed in generators is 1:1 mapping of containers to route. Where as _my_ default approach is to compose route markup from multiple containers e.g. `/` would be:

```
<div>
    <AddUserForm />
    <UserList filter={e=>e.type == 'admin' || e=>e.type == 'user' }/>
</div>
```

And then I would reuse `<UserList filter={fn} />` throughout the site.

So my instinct would be to never use the injecting in `app/routes.js` provided by the generator. I would _always_ use the method expressed above. And I'd modify the generators accordingly.

**Question**: Does that set off alarm bells for anyone here? Or is this a completely valid approach?

**Comment by dcarneiro** [comment]
I've had some trouble while implementing @bobkocisko [solution](https://github.com/mxstbr/react-boilerplate/issues/537#issuecomment-235065705) and @learntoswim [solution](https://github.com/mxstbr/react-boilerplate/issues/537#issuecomment-235068751) mainly because: 

- `injectSagas`is now expecting an Array
- the store was not valid right after `store.runSaga = sagaMiddleware.run;` => `asyncInjectors: Expected a valid redux store)`
- `sagaMiddleware.run(...globalSagas);` wouldn't accept more than one saga.

What I finally ended up to have multiple global sagas was to create a *sagas.js on the app folder:

```javascript
import { getAsyncInjectors } from './utils/asyncInjectors';

import { loginSaga } from './containers/Login/sagas';
import { categorySelectorSaga } from './containers/CategorySelector/sagas';

export function injectGlobalSagas(store) {
  const { injectSagas } = getAsyncInjectors(store);

  injectSagas([
    loginSaga,
    categorySelectorSaga
  ]);
};
```

And call the `injectGlobalSagas` right before creating the routes on *app.js*:

```javascript
import createRoutes from './routes';

import { injectGlobalSagas } from './sagas';
injectGlobalSagas(store);

const rootRoute = {
  component: App,
  childRoutes: createRoutes(store),
};
```

**Comment by rezadhah** [comment]
hello, i'm trying to inject my global saga in store.js like @learntoswim way in [comment =] (https://github.com/react-boilerplate/react-boilerplate/issues/537#issuecomment-235068751)

so the idea is, i'm trying to dispatch an action that will trigger my global saga onEnter hook in react router. but i dont know why it only run once in initial state of the apps. 

so this is my routes.js

```
route.onEnter = function onEnter(nextState, replace, callback) {
      store.dispatch(doSomething());
      if (importSaga !== false) {
        if (this.loadedSagas) {
          callback();
        }
        const importModules = importSaga.call();
        importModules.then((sagas2) => {
          this.loadedSagas = injectSagas(sagas2.default);
          callback();
        });
        importModules.catch(errorLoading);
    };
}
```
so why does my global saga only run once if i try to move to another route?
ty for your attention :D
