### ISSUE TITLE
Using selector creators vs selectors

### ISSUE THREAD

**Issue by igorbarbashin** [mxstbr/react-boilerplate#617]
I'm curious what was the reason behind returning a function in selectors rather than returning the actual selector.

Example:
```javascript
// Selector
const selectRepos = () => createSelector(
  selectGlobal(),
  (globalState) => globalState.getIn(['userData', 'repositories'])
);
```

```javascript
// Container
const mapStateToProps = createStructuredSelector({
  repos: selectRepos(),
});
```

Why not to use selectors directly?

```javascript
// Selector
const selectRepos = createSelector(
  selectGlobal,
  (globalState) => globalState.getIn(['userData', 'repositories'])
);
```

```javascript
// Container
const mapStateToProps = createStructuredSelector({
  repos: selectRepos,
});
```

The benefit would be to access ownProps in the selectors. 
So I could do something like that:
```javascript
export const selectUserIdFromRoute = (_, props) => props.params.userId;

export const selectUserOnRoute = createSelector(
  [
    selectUsersState,
    selectUserIdFromRoute,
  ],
  (users, id) => users.get(id)
);
```

Am I missing some point? Is it an anti-pattern?

**Comment by mxstbr** [comment]
> Am I missing some point? Is it an anti-pattern?

It is indeed, because we might reuse the selector.

If you use the same instance of the selector (which you do in the second case), it **cannot memoize the properties**. That means you essentially loose all the benefit of `reselect` by doing that!

See the [`reselect` FAQ](https://github.com/reactjs/reselect#q-can-i-share-a-selector-across-multiple-components) for more information!
