### ISSUE TITLE
Consider React storybook to enable stand alone component viewing/prototyping.

### ISSUE THREAD

**Issue by bcowgill** [mxstbr/react-boilerplate#640]
I've been using the React storybook to allow me to view my components outside the application.

https://github.com/kadirahq/react-storybook

It's quite useful to set up your component in every possible render state and preview how it looks and operates within the story book prototyping tool.

If you're interested I have some commits to install storybook in boilerplate, preview the A component in the story book and npm generator changes to create the story harness file when you create a new component.

**Comment by mxstbr** [comment]
You heard that I helped make https://github.com/carteb/carte-blanche?

We're working on the `react-boilerplate` integration at the moment, should be finished soon hopefully!

**Comment by bcowgill** [comment]
No, I haven't seen that. I'll give it a try.

**Comment by mikeloll** [comment]
@bcowgill Would you mind sharing the diffs to get storybook working as a gist?

**Comment by marc-rutkowski** [comment]
@mikeloll Hope this help: https://gist.github.com/marc-rutkowski/48fa77fdc9439588ce4a3665137fb018

**Comment by armand1m** [comment]
I've forked the last master branch and integrated it with React Storybook and Storyshots. Implemented some cool features such as the generation of `.story.js` files in the components folder in which leads to instant component development and prototyping, as this gif shows:

![storybook-2](https://cloud.githubusercontent.com/assets/6154901/22859097/6c5dfc48-f0b8-11e6-8f38-e33cf303ff8d.gif)

I've also edited the documentation and created some files to document the new npm scripts I've created to make this experience good (at least to me).

https://github.com/armand1m/react-boilerplate

**Comment by marc-rutkowski** [comment]
@armand1m It looks great!

**Comment by eric-burel** [comment]
@armand1m Do you plan to document your changes ? This would be great to have a FAQ section about storybook, and your implemention sounds just amazing.
Having it merged directly could also be great.

**Comment by armand1m** [comment]
@eric-burel My changes are already documented in the project, you can see the [fork features](https://github.com/armand1m/react-boilerplate#this-forks-features) at the README.

Also, in the [Documentation Section](https://github.com/armand1m/react-boilerplate#documentation) you can find the sections explaining how to run your Storybook and your Storyshots.

https://github.com/armand1m/react-boilerplate/blob/master/docs/storybook
https://github.com/armand1m/react-boilerplate/blob/master/docs/storyshots

At the [Commands Section](https://github.com/armand1m/react-boilerplate/blob/master/docs/general/commands.md#storybook), you can find the Storybook `npm` commands as well.

I've made some changes to the `generate` script as well. When generating a component, it creates a folder inside the component folder called `stories`, with a Storybook template called `index.story.js` inside this folder. It is the only thing not documented.

Besides that, I made a change where I can tell the `generate` script if my component is composed with other independent components from my project. If it is a composed component, it creates the component inside a folder called `compositions`, if it is not, it will be created inside the `components` folder. I like this because I can separate the trully independent presentational components from my application, from the ones who depends in other internal components, but still have no logic.
