### ISSUE TITLE
What's the best way to persist state to localStorage or some other storage medium?

### ISSUE THREAD

**Issue by yookore** [mxstbr/react-boilerplate#652]

**Comment by gihrig** [comment]
Not sure about _best_, but [redux-persist](https://github.com/rt2zz/redux-persist) tackels that problem.

**Comment by fforres** [comment]
The persistance model that [redux-persists](https://github.com/rt2zz/redux-persist) uses, it's based on persisting the whole store (Blacklisting or Whitelisting) specific reducers.

I've been toying aroung with [redux-storage](https://github.com/michaelcontento/redux-storage), it uses a reducer enhancer instead of a store enhancer for persitance (https://github.com/rt2zz/redux-persist/issues/130)

Any ideas @yookore @gihrig are welcome :)

**Comment by gihrig** [comment]
Nothing new to add, but the contribution is appreciated 😃 

Let us know how your chosen persistence method works out.

**Comment by gustavo-depaula** [comment]
Hello guys! How do I use redux-persists or redux-storage with react-boilerplate?
