### ISSUE TITLE
net::ERR_INSECURE_RESPONSE error.

### ISSUE THREAD

**Issue by suhaotian** [mxstbr/react-boilerplate#669]
Fixed with [https://github.com/NekR/offline-plugin/issues/77](https://github.com/NekR/offline-plugin/issues/77) config.

**Comment by mxstbr** [comment]
Can this be closed @suhaotian? (Ref #670)

**Comment by suhaotian** [comment]
@mxstbr Yes 😄

**Comment by chaintan17** [comment]
I spent quite few time (hours) fixing this bug also.
Is it better to have relativePath disable by default ?
it's not so obvious bug (happened only in production) and it's hard to investigate.

**Comment by suhaotian** [comment]
@chaintan17 You can do it in your config file 😸

**Comment by chaintan17** [comment]
Yes i know, i just asking for set it as default.
Since newbie like me spent quite few time discover and fixing this bug... :(

**Comment by gihrig** [comment]
`Is it better to have relativePath disable by default ?`

What advantage do we gain by having relative paths enabled?

At the very least this should be documented.

**Comment by chaintan17** [comment]
I will ask the maintainer of offline plugin instead.

**Comment by NekR** [comment]
In case someone is interested in it, I answered questions about `relativePaths` here: https://github.com/NekR/offline-plugin/issues/77#issuecomment-234642483

Regarding questions "Why `relativePaths` are `true` in `react-boilerplate`", well, because no one passed `publicPath` to `offline-plugin` options. I personally don't use React or `react-boilerplate`, so I just contributed my part related to `offline-plugin` here. If `react-boilerplate` already uses `publicPath` by default, then it's totally fine to set it for `offline-plugin` too (with `relativePaths` to `false`, of course).

As I said in explanation comment, `relativePaths: true` is reasonable default setting, this is why it's `true` by default :-)

**Comment by gihrig** [comment]
@NekR Thanks! That helps to clear things up.

@mxstbr Do you see any reason not to change to  `relativePaths: false` in react-boilerplate?

**Comment by mxstbr** [comment]
Not as far as I can tell @gihrig, PR?

**Comment by gihrig** [comment]
@chaintan17 I was unable to reproduce the error in my environment. Can you test the PR please?

If you're unsure how to checkout a PR, see "command line instructions" near the bottom of the PR page.

Thanks.

**Comment by NekR** [comment]
Just to clear it: `net::ERR_INSECURE_RESPONSE`  error isn't the cause or something like that. This error just says that SW was served with wrong mime type or other value. Which in case of relative paths and sub-directory means that server returns 404 with HTML mime type.

**Comment by gihrig** [comment]
I observed Chrome Network tab while loading, reloading in a production build. No 404's occurred before or after.

**Comment by chaintan17** [comment]
Yes, i confirmed that the problem disappear now.
Thank you for the pull request and clear explanation @NekR @gihrig, i appreciated.

**Comment by gihrig** [comment]
@chaintan17 Thank you for your effort in bringing this forward to a solution!

**Comment by mhrisse** [comment]
Hi! Might this console warning be related? (just cloned right now): 
![screen shot 2016-07-24 at 21 13 08](https://cloud.githubusercontent.com/assets/1583014/17085868/947ca0d6-51e3-11e6-96a6-7fa908ff563b.png)

**Comment by NekR** [comment]
Warning is related to this: https://github.com/NekR/offline-plugin/issues/74, it's basically a safe guard. Warning means that `offline-plugin/runtime` was included in the bundle, but `OfflinePlugin` instance wasn't added to webpack's plugin list. There is nothing bad about that, it's just informational warning.

If this warning seems confusing, I'm always open to suggestions.

**Comment by mhrisse** [comment]
Hi! Thanks for getting back to me so swiftly. 

From my point of view, I do not expect a freshly cloned boilerplate to throw any warnings. It's like buying a new car and something light is blinking on the dashboard (I know, bad example). 

If it has to be warning, then I would suggest from a developer ergonomics perspective a link to a page or github issue clearly explaining what this warning is about and what the implications are. (I am still wondering what this means for the offline capabilities of my future webapp?). I guess this is the same React does now and I always liked about requirejs warnings.

**Comment by NekR** [comment]
@mhrisse Yeah, I agree it weird to have warnings in freshly-cloned boilerplate. 

> If it has to be warning, then I would suggest from a developer ergonomics perspective a link to a page or github issue clearly explaining what this warning is about and what the implications are. 

This is good idea :-) But for this particular situation it doesn't have to be a warning, we can simply pass an instance of `OfflinePlugin` which does nothing in dev mode, like this:

```js
new OfflinePlugin({
  AppCache: null,
  ServiceWorker: null
})
```

Well, it will do some stuff because there is no direct "disabled" switch right now, but at least it won't generated any assets and will make runtime to not try install AppCache/SW, while still removing the warning because we explicitly added `OfflinePlugin` to the build.

> I am still wondering what this means for the offline capabilities of my future webapp?

Warning means that `offline-plugin` is disabled, in this particular case, because you are in dev mode.
