### ISSUE TITLE
Heroku deploy failing, presumably due to state of package.json

### ISSUE THREAD

**Issue by Jan-Jan** [mxstbr/react-boilerplate#807]
Thank you for react-boilerplate!!!

## Description

Heroku install is failing, I presume it is due to the package.json having unmet peer dependencies.

## Steps to reproduce

Download latest version.
Follow steps in https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/deployment.md

# Versions

- Node/NPM: 6.2
- Browser: irrelevant

**Comment by gihrig** [comment]
@Jan-Jan Can you provide more info on how Heroku deploy fails, e.g. any errors, and why you think unmet peer deps might be the cause?

As far as I have seen, unmet peer dep errors happen when package 'A' expects dep 'B' of version 'x', but 'B' of version 'x+' (beyond 'A's semver range)  is available. In local testing and Travis/AppVeyor builds, these 'errors' do not cause a problem.

I have no experience with Heroku.

**Comment by mxstbr** [comment]
As @gihrig said, we won't really be able to help you without any logs. :+1:

**Comment by sethmcleod** [comment]
@Jan-Jan My advice is to do a detailed review of your imports and directory folders. I was recently having trouble with Heroku deployment as well, and the error logs don't really give any helpful information _(looking almost exactly like this: https://github.com/mxstbr/react-boilerplate/issues/700_).

After an hour of head bashing I finally realized that I had accidentally moved my _fonts_ folder into another folder, so that was causing the build process to fail. Oddly enough it wasn't affecting my dev server, but I was able to figure it out by back tracking through my recent commits and running `npm run build` locally to make sure it wouldn't fail.

If that doesn't help at all, check out my comment here: https://github.com/mxstbr/react-boilerplate/pull/743#issuecomment-234756677. I was initially having trouble deploying to Heroku because `npm run build` was triggering `postbuild` which was triggering `npm run test`. Karma was failing and crashing the build because there is no Chrome binary on the platform. I was able to get around this by removing the test script from the _prebuild_ step so it looked like this: `"prebuild": "npm run build:clean",`. 

Obviously that isn't really a solution if you need Karma tests to be run on deployment, but it may help point you in the right direction.

Good luck!

**Comment by mxstbr** [comment]
Why does webpack not show a helpful error in that case?! @TheLarkinn

**Comment by Jan-Jan** [comment]
No helpful errors from Heroku at all :-(

**Comment by Jan-Jan** [comment]
@sethmcleod tried that, didn't work (but, worth adding to the docs I think)

We can close this ticket, because I gave up and deployed to gcloud instead.
