### ISSUE TITLE
Handling re-caching after new application version deployment?

### ISSUE THREAD

**Issue by IljaDaderko** [mxstbr/react-boilerplate#852]
I found myself deploying code to production today and not seeing any updates in the application, only after I deleted all cache in the website I was able to see my changes leading to my question. What is correct way to handle re-cache of the website when new feature is deployed to production?

**Comment by mxstbr** [comment]
Well the one thing you really want to uncache is the `index.html` file. Since it references the new files, once users get the new version of that they'll have the new version of the app.

Not sure if that answers the question? I guess an automatic setup would be nice but that strongly depends on how you deploy…

**Comment by IljaDaderko** [comment]
@mxstbr Sure thing, but I'm just thinking of how to actually achieve it, i.e. assume deployment to heroku for example, what can the steps / places be where I'd need to do un-caching? is it on the serverside or can I do it during build?

**Comment by elswenson** [comment]
I ran into similar issues when using this boilerplate for an application served as static pages. The offline plugin made browsers run the scripts from the cached worker rather than grabbing a new one from the host (until I manually cleared them from the browser cache); even if each item in the build had a hashed name and the CDN was configured for a short cache period.

**Comment by mxstbr** [comment]
That should definitely not happen! @NekR any ideas?

**Comment by NekR** [comment]
Well, this question is raised each month or so. Here is the answer: https://github.com/NekR/offline-plugin/blob/master/docs/updates.md

If that doc doesn't help, please provide detailed steps about how you are trying to update website. All steps, e.g. what you do with build and what you do with browser.

**Comment by maheffa** [comment]
I'm facing the same issue with my project. For some reason, `index.html` doesn't get updated. I always end up loading the old version of it, which points to a different `main.<hash>.js` than what have been generated during the latest build. I always have to do an `Empty cache and hard reload` on Chrome in order to get the correct version.

**Comment by NekR** [comment]
Again, this doesn't help without details. All what you describe is a
problem in general which could even not a problem, but just understanding.
Please if you post in this thread, confirm that you read mentioned doc and
steps described there didn't help you. Thanks.

**Comment by NekR** [comment]
@mxstbr 
> Well the one thing you really want to uncache is the index.html file. Since it references the new files, once users get the new version of that they'll have the new version of the app.

I don't think it's the issue. HTML files might be cached and it's totally fine.

**Comment by NekR** [comment]
@mxstbr should we close this?

**Comment by elswenson** [comment]
Since you said this question is raised every month or so, would it make sense for there to be even just a small note in the documentation for react-boilerplate to seek out the documentation for offline-plugin? 

While finding the library documentation is an obvious next-step for more experienced developers, it might reduce the redundant questions, if nothing else?

**Comment by NekR** [comment]
@elswenson it probably makes sense, but it's up to this' repo maintainers to add it or not. If there is a FAQ or _Notes_ section somewhere here, when that would be perfect place for such a note.

**Comment by mxstbr** [comment]
Yeah sure, there is a FAQ! A PR adding this to the FAQ would be much appreciated :+1:

**Comment by NekR** [comment]
@mxstbr if I'll have time, too much to handle already 🙂

**Comment by gihrig** [comment]
> @mxstbr Well the one thing you really want to uncache is the index.html file. Since it references the new files, once users get the new version of that they'll have the new version of the app.

> @NekR I don't think it's the issue. HTML files might be cached and it's totally fine.

> @NekR if I'll have time, too much to handle already

@NekR Could you provide a rough outline of what you had in minder to add to the FAQ? Then others can polish it up and open a PR. - Thanks

**Comment by NekR** [comment]
@gihrig I meant something like this: "Your production site isn't working? You update the code and nothing changes? It drives you insane? Here is the answer -- https://github.com/NekR/offline-plugin/blob/master/docs/updates.md"

**Comment by gihrig** [comment]
@NekR That's perfect, thanks!

@Vadorequest Would you like to open a PR with these changes to [FAQ.md](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md) ?

**Comment by Vadorequest** [comment]
@gihrig Done at https://github.com/mxstbr/react-boilerplate/pull/1081

**Comment by gihrig** [comment]
[FAQ](https://github.com/mxstbr/react-boilerplate/blob/dev/docs/general/faq.md#issue-with-local-caching-when-running-in-production-mode-f5--ctrlf5--cmdr-weird-behavior) updated.

Thanks @Vadorequest 🎉
