### ISSUE TITLE
Consider npm-shrinkwrap

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#873]
Recently there have been project build breakages that appear to be related to unexpected dependency version changes ref #864.

Some time ago dependencies were 'pinned', abandoning semver #598. While this has presumably  prevented unexpected version shifts of 'top level' dependencies there is still the matter of 'sub level' dependencies using semver and changing beyond control of this project.

I'm exploring the use of `npm shrinkwrap` to lock down all dependency versions. But shrinkwrap has not seen wide use in open source projects, that I can see. There's even a (somewhat) well reasoned [rant](http://jonnyreeves.co.uk/2016/npm-shrinkwrap-sucks/) against its use (sort of)...

Uber created a A [consistent shrinkwrap tool](https://github.com/uber/npm-shrinkwrap), but that seems to be languishing.

So, I'm interested in hearing experience, good or bad with `npm shrinkwrap` or `uber/npm-shrinkwrap` and any opinions on it's use in this project.

All input is appreciated.

**Comment by mxstbr** [comment]
I like the idea, since in a production environment you'd want to do that too. The question is, can we pull it off in a nice way?

**Comment by insin** [comment]
During the left-pad thing I tried shrinkwrap and [shrinkpack](https://github.com/JamieMason/shrinkpack) to salvage a CI build, only to find npm2 was installing `peerDependencies` into every project which declared them, which broke React. I think a fixed version was included by default with a recent Node v4 release, but you would need to check users' npm version carefully.

**Comment by mxstbr** [comment]
We only allow `npm > 3` already because of `peerDependency` errors, so that's fine. (which we have tons of due to webpack v2 not being released yet)

**Comment by gihrig** [comment]
I had hoped to include a `shrinkwrap.json` file in this week's dependency update, several problems have come up.

The problems center around `npm shrinkwrap`'s refusal to support extraneous or out-of-range  dependencies.

Some example errors:
```
npm ERR! peer invalid: webpack@^1.9.11, required by extract-text-webpack-plugin@1.0.1
npm ERR! extraneous: react-boilerplate-dlls@3.0.0 /Users/glen/Documents/JavaScript/Research/react-boilerplate/node_modules/react-boilerplate-dlls
npm ERR! peer invalid: history@^1.12.1 || ^2.0.0, required by scroll-behavior@0.7.0
```

1. webpack@2.1.0-beta.15 does not satisfy the requirement for webpack@^1.9.11 ( in npm's view).
2. react-boilerplate-dlls@3.0.0  should not be pre-packaged with react-boilerplate, but having them in `node_modules` will result in their removal on subsequent `npm install`s.
3. Expanding on 2 above, when developers add new packages, the presence `shrinkwrap.json`  will cause problems.

Ref:
1. npm/npm [Install multiple versions of a dependency #5499](https://github.com/npm/npm/issues/5499) (long read).
2. and 3. npm/npm [ In npm@^3, extraneous packages are removed if npm-shrinkwrap.json present #11682](https://github.com/npm/npm/issues/11682) (long read).

There may be a solution in packaging a `shrinkwrap.json` with the project and deleting it at the end of `setup`, But this does not solve all the problems, and will apply only to the initial install. It will likely create confusion in some unforeseen way.

**Comment by Augustin82** [comment]
We were using 3.0.0 and, when installing on a brand new machine last week, everything stopped building, apparently because of transverse dependencies. So we had to move to 3.1.0 to sort dependency problems and I decided to prevent future problems by using shrinkwrap.

I have managed to make shrinkwrap happy by making as few changes as possible on 3.1.0 :
- in `package.json`
```
-	    "history": "3.0.0",
+	    "history": "2.1.2",
-	    "eslint-plugin-import": "1.12.0",
+	    "eslint-plugin-import": "1.13.0",
-	    "extract-text-webpack-plugin": "1.0.1",
+	    "extract-text-webpack-plugin": "2.0.0-beta.3",
-	    "webpack": "2.1.0-beta.15",
+	    "webpack": "2.1.0-beta.19",
```

- in `internals/webpack/webpack.prod.babel.js`
```
-	  cssLoaders: ExtractTextPlugin.extract(
-	    'style-loader',
-	    'css-loader?modules&-autoprefixer&importLoaders=1!postcss-loader'
-	  ),
+	  cssLoaders: ExtractTextPlugin.extract({
+	    fallbackLoader: 'style-loader',
+	    loader: 'css-loader?modules&-autoprefixer&importLoaders=1!postcss-loader',
+	  }),
```

So, unless I've forgotten something, if you make those changes to 3.1.0 and then `npm install` afresh, you should then have a working boilerplate that's `npm shrinkwrap`-able.

Please let me know if something above seems wrong.

**Comment by gihrig** [comment]
@Augustin82 Thanks for the input!

I'm concerned about this, from the OP in  [In npm@^3, extraneous packages are removed if npm-shrinkwrap.json present #11682](https://github.com/npm/npm/issues/11682), linked above.

>  If you have npm-shrinkwrap.json present, any packages you install manually via npm are removed if you run npm i again, because they are not in the shrinkwrap file.

Have you taken this into consideration?

**Comment by Augustin82** [comment]
@gihrig you're most welcome.

I have not thought much about this. I know shrinkwrap is somewhat of a pain to maintain, but after having spent a whole day on deps issues, I'm inclined to say it's worth it.

From what I read in the issue you linked, it's only a problem for manually-installed packages. We do not do that: our packages are either a dependency or a devDependency, and I have used `npm shrinkwrap --dev` (since the point was to have the same setup across all our dev/test machines).

I have not tested how `npm shrinkwrap` behaves when optionalDependencies, but apparently [not very well](https://github.com/npm/npm/pull/13579).

My only beef with shrinkwrap for now, apart from the added maintenance, is that it does not enforce a package version if a superseding one installed. So, earlier, I wanted to check if webpack@2.1.0-beta.21 fixed a minor annoyance compared to webpack@2.1.0-beta.19, and I had to manually `rm -rf node_modules/webpack` to revert to my shrinkwrapped dependency.

**Comment by gihrig** [comment]
@Augustin82 In your situation it sounds like [shrinkpack](https://github.com/JamieMason/shrinkpack) or even a local private npm registry such as [sinopia](https://www.npmjs.com/package/sinopia) might be a good solution.

In this issue I'm exploring possible ways to provide the benefits of a private registry to react-boilerplate users without their having to configure and maintain anything. It doesn't look that's going to work out.

**Comment by Augustin82** [comment]
A noble goal, and I'm definitely going to look into sinopia, because we (obviously) could benefit from that kind of system.
As for react-boilerplate users, I still think that the few changes I've described and the use of shrinkwrap would be simple enough (and not too much added trouble) in exchange for decreased likelihood that, suddenly, the build process will no longer work.

**Comment by palmerj3** [comment]
I have a few issues with shrinkwrap. My biggest issue is that simply having a file named npm-shrinkwrap.json in the root of your project changes the behavior of NPM such that anyone interacting with your project needs to know about shrinkwrap in order to manage dependencies.

Aside from that shrinkwrap does not do the one thing it is supposed to do: provide the exact same dependency tree on every install using the same shrinkwrap file. OptionalDependencies are the main issue here as the above referenced PR explains. You may not be explicitly defining any optional dependencies but it's pretty likely you will have fsevents in your dependency tree which is an OS X only native extension so it's often included as an optional dependency which NPM will simply skip over if installation fails. The effect of having a dependency like this in your tree is that if you generate your shrinkwrap on linux you will never get this dependency in the shrinkwrap file. If you generate it on OS X you will have it but it will only be installable on OS X. So you have a situation already where different dependencies are used across platforms making shrinkwrap fundamentally flawed.

The other issue I have with shrinkwrap is that it doesn't include the shasum of the packages in the shrinkwrap file so I do not think shashums are validated on install with shrinkwrap.. I'm not entirely sure about that so would need to do some more digging but I do know there is a proposal to add shasum to the generated shrinkwrap file.

Hope this helps..

**Comment by Augustin82** [comment]
> I have a few issues with shrinkwrap. My biggest issue is that simply having a file named npm-shrinkwrap.json in the root of your project changes the behavior of NPM such that anyone interacting with your project needs to know about shrinkwrap in order to manage dependencies.
How so? Don't they simply do "npm install" to have it run? And if they need to contribute, then yeah, they need to read about it in the guidelines or something. Or am I missing something else? Obviously, I'm very interested in any drawback I may have missed, since we will be using this in production.

> Aside from that shrinkwrap does not do the one thing it is supposed to do: provide the exact same dependency tree on every install using the same shrinkwrap file. OptionalDependencies are the main issue here as the above referenced PR explains. You may not be explicitly defining any optional dependencies but it's pretty likely you will have fsevents in your dependency tree which is an OS X only native extension so it's often included as an optional dependency which NPM will simply skip over if installation fails. The effect of having a dependency like this in your tree is that if you generate your shrinkwrap on linux you will never get this dependency in the shrinkwrap file. If you generate it on OS X you will have it but it will only be installable on OS X. So you have a situation already where different dependencies are used across platforms making shrinkwrap fundamentally flawed.
That is true. It is a non-issue for our setup, where all our machines are Linux-based, but obviously a lot of people use OSX in development, so it's definitely a concern.

> The other issue I have with shrinkwrap is that it doesn't include the shasum of the packages in the shrinkwrap file so I do not think shashums are validated on install with shrinkwrap.. I'm not entirely sure about that so would need to do some more digging but I do know there is a proposal to add shasum to the generated shrinkwrap file.
There are packages aiming to do that ([lockdown](https://github.com/mozilla/npm-lockdown) and [seal](https://github.com/zaach/npm-seal)) but they are positiviely ANCIENT, so they're probably not safe for use...

Any alternative solution, short of committing the deps? (Then again, we have less than 300MB, so it might be worth it... Hmm.)

Thanks for the feedback @palmerj3, it's appreciated =)

**Comment by palmerj3** [comment]
@Augustin82 yeah my first point is mostly about developer training. Suddenly having this file means that they all need to know exactly how shrinkwrap works in order to update dependencies. Can't just modify your package.json manually and have it work..

Regarding lockdown and seal they really aren't necessary if you have shasums for the tarballs.

Committing your node_modules still leaves you with the same optionalDependency problem, actually :)  Also you will need to call `npm rebuild` after every pull. 

The best solution for shrinkwrap IMO is to remove optionalDependencies from the shrinkwrap file entirely. Some people are already doing this - example: https://github.com/npm/npm/issues/2679#issuecomment-219103907

Or if you have a look at my PR referenced above I modified NPM to exclude optional deps from shrinkwrap.

**Comment by JamieMason** [comment]
if it helps any, [shrinkpack](https://github.com/JamieMason/shrinkpack) now removes optionalDependencies by default.

**Comment by palmerj3** [comment]
@JamieMason well done, sir :)

**Comment by mxstbr** [comment]
With our yarn lockfile, I'm pretty sure we won't need shrinkwrap anymore, so I'll close this for now. Thank you for the very interesting discussion, I'll definitely refer to it a bunch in the future!

**Comment by brandondurham** [comment]
FWIW, `npm-shrinkwrap` has been kind of a nightmare for us at Hoefler & Co. It’s incredibly clunky and often doesn’t even work. For instance, we installed the same package on two machines with the same repo and `npm-shrinkwrap.json` file. One machine picked up the install and updated the reference in `npm-shrinkwrap.json`, the other did not.

This happens often.

I would love to hear how people have been feeling about Yarn. We’re considering switching for this very reason, but are a bit leery considering its age.

**Comment by gihrig** [comment]
> I would love to hear how people have been feeling about Yarn.

@brandondurham 

Mage the switch for installs, never looked back. Highly recommended!

**Comment by KarandikarMihir** [comment]
@brandondurham We've had really bad experience with npm-shrinkwrap in our project. At first, we were reluctant, but once we switched to yarn, it started working like a charm! Even `react-boilerplate` has had to face some issues related to npm. But yarn has never failed us.

> One machine picked up the install and updated the reference in npm-shrinkwrap.json, the other did not.

Faced the exact same problem.
