### ISSUE TITLE
Nesting selectors inside empty function?

### ISSUE THREAD

**Issue by Dattaya** [mxstbr/react-boilerplate#882]
Is there any reason behind nesting a selector inside an empty function?
For example, this code:
```js
const selectGlobal = () => (state) => state.global;

const selectCurrentUser = () => createSelector(
  selectGlobal(),
  (globalState) => globalState.currentUser
);
```
could be rewritten like so:
```js
const selectGlobal = (state) => state.global;

const selectCurrentUser = () => createSelector(
  selectGlobal,
  (globalState) => globalState.currentUser
);
```
same for `selectCurrentUser`.
Another question that I have is `selectCurrentUser` doesn't perform any heavy computations. Was it memoized just as a showcase of how to use `reselect`?

**Comment by mxstbr** [comment]
> Was it memoized just as a showcase of how to use reselect?

Yes, and because it can't hurt to memoize it 😉 

> Is there any reason behind nesting a selector inside an empty function?

You tell me, I was under the impression that was necessary but I might be wrong!

**Comment by loicginoux** [comment]
I was also wondering and I just found hte article on the  [Redux doc](http://redux.js.org/docs/recipes/ComputingDerivedData.html) explaining why this is necessary. Mystery solved ! :)

**Comment by Dattaya** [comment]
Thanks, @mxstbr that's a much better name for this topic :).
> Yes, and because it can't hurt to memoize it :wink:

Maybe a tiny bit because we have one additional function call and one `if`.

> You tell me, I was under the impression that was necessary but I might be wrong!

I'll send a new pull request.

> I was also wondering and I just found hte article on the Redux doc explaining why this is necessary. Mystery solved ! :)

Redux docs' examples don't have selectors inside an empty function either:

```js
const getKeyword = (state) => state.keyword

const getVisibleTodosFilteredByKeyword = createSelector(
  [ getVisibleTodos, getKeyword ],
```

**Comment by mxstbr** [comment]
Sorry for all the work that didn't get merged, and thanks for taking the time to submit this PR! Glad we've got a solid line of reasoning now. :+1:

**Comment by kachkaev** [comment]
Thanks for starting this discussion guys. I was a bit sceptical about an extra `() =>` for each selector and just checked the consequences of this. Try this as well!

```js
const selectSomethingThatManyOtherSelectorsDependOn = () => createSelector(
  selectSomeDomain(),
  (substate) => substate.get('something') * 42,
);
```
↓
```js
const selectSomethingThatManyOtherSelectorsDependOn = () => createSelector(
  selectSomeDomain(),
  (substate) => console.log('recomputing selector...') || (substate.get('something') * 42),
);
```

After `someDomain` that contains `something` has been changed in your state, you'll see a lot of log statements, because all your selectors and their children will have a new isolated instance of `selectSomethingThatManyOtherSelectorsDependOn`. It is being created every time `selectSomethingThatManyOtherSelectorsDependOn` is mentioned as an argument with `()` in another selector. The value of `something` will be cached, but not just once as you would expect.

Wrapping `createSelector` into an extra `() =>` only makes sense if some selector depends on the props. In this case we could use `makeSelectMyStuff` instead of `selectMyStuff`. So you'll never become confused about whether to add `()` when a selector is an argument or not:
```js
/* ... */ createSelector(
  selectA,
  makeSelectB(/* props? */),
  (a, b) => /* ... */
)
```

How about switching to this convention? Adding `make` is what they do in the [official `reselect` docs](https://github.com/reactjs/reselect).

**Comment by kachkaev** [comment]
One little thing to note when removing `() =>` is that the selectors in different components can no longer be cross-referenced. I.e. if we have `containers/A/selectors` and `containers/B/selectors` and `selectSomethingFromA` references `selectSomethingFromB`, then `selectSomethingElseFromB` can no longer depend on `selectSomethingElseFromA`. This should not happen in a small or a well-structured app, however I managed to face the problem in a rather complex dashboard to which I was adding extra features over time.

The thing is that when we have `() => `, `createSelector` calls are sort of deferred until all the modules are loaded. If we just use plain `createSelector`, all its `selectX` arguments have to be functions immediately, which is not possible if two javascript files import stuff from each other.

It's still worth getting rid of `() =>` for all selectors except those that are component-specific, because this will make an app faster in old browsers and even more energy-efficient on mobile devices :–)

**Comment by Dattaya** [comment]
With `make` in front it's clear where a selector is and where a selector factory. What do you think @mxstbr?

**Comment by mxstbr** [comment]
> With make in front it's clear where a selector is and where a selector factory. What do you think @mxstbr?

Yes, you've convinced me, let's do that! Would appreciate a PR!

**Comment by spentay** [comment]
Just checking in on the status & current thoughts on this? Just awaiting a PR?
cc: @mxstbr @Dattaya & @kachkaev :)

**Comment by Dattaya** [comment]
It's not a bug so I wasn't in a hurry. @spentay, if you want, you can fix this instead of me.

**Comment by spentay** [comment]
Thanks for being so quick @Dattaya!  
I've still got a lot of reading to do on the subject before I'm fully comfortable with a PR - I will shoot an update here if I do end up kicking it off though!

**Comment by Dattaya** [comment]
This is going to be easy:
- All selectors of type `const selectUsername = () => createSelector(` should be renamed to `makeSelectUsername`
- All other regular selectors should be unwrapped: `const selectHome = () => (state) => state.get('home');` => `const selectHome = (state) => state.get('home');`

**Comment by kachkaev** [comment]
@Dattaya one more thing: when regular selectors are mentioned as arguments in other selectors, brackets should be removed (`selectAbc(),` → `selectAbc,`). `createSelectXyz()` should keep brackets.

**Comment by Dattaya** [comment]
Almost done in #1205. Took more time than anticipated because of generators, templates, and documentation. Thank you, everyone who participated in the discussion :+1:.
