### ISSUE TITLE
Using a different server with react-boilerplate

### ISSUE THREAD

**Issue by mkolodny** [mxstbr/react-boilerplate#899]
I would like to use my own custom Django server instead of the default Node server. What's the recommended way to do that with react-boilerplate?

I saw [this pull request](https://github.com/mxstbr/react-boilerplate/pull/679), which uses proxy requests. If possible, I'd prefer to make requests directly to my server. Is that possible with react-boilerplate?

**Comment by theotow** [comment]
hey @mkolodny,

would be helpful if you can outline your setup with some more details to answer better.

Instead of serving filer in the 'build' folder with nodejs you can do that with Django, i think it just needs some webpack adjustments to be able to keep hot reloading etc. working properly and to tell webpack not to write files to memory

Let me know if you have further questions
