### ISSUE TITLE
Autoprefixer (cssnext) not working properly

### ISSUE THREAD

**Issue by billyshena** [mxstbr/react-boilerplate#911]
Hello everyone ! I'm currently facing issues regarding the autoprefixer (used from cssnext module).
Using a clean project based on react-boilerplate, if I try something like this:

transform: translate(-50%,-50%); // -> no prefixes added
display: flex // -> only -ms- prefix is added but no -webkit- prefix

Is it an expected behaviour?

Best,

**Comment by gihrig** [comment]
From [autoprefixer](https://www.npmjs.com/package/autoprefixer) npm page:

> PostCSS plugin to parse CSS and add vendor prefixes to CSS rules using values from Can I Use

I actually don't know. What does Can I Use say about those properties?

**Comment by billyshena** [comment]
If you try https://autoprefixer.github.io, you will see that it's correctly prefixing those attributes

// display flex using autoprefix.github.io
display: -webkit-box;
display: -ms-flexbox;
display: flex;

// display flex using react-boilerplate
display: -ms-flexbox;
display: flex;

Missing -webkit-box when I use this boilerplate

**Comment by elswenson** [comment]
@billyshena If you look at the webpack config files in the boilerplate, you will see the postcss settings are set to:
`cssnext({ browsers: ['last 2 versions', 'IE > 10'], })`

If you use these settings on https://autoprefixer.github.io, you will see that the -webkit-box prefix will not appear. It would look like this is the expected behavior for these settings, you can adjust those settings in the webpack config files to your needs. (For example, if you need to support older browsers or older versions of IE). 

The config files are currently under /internals/webpack

I hope that helps clear things up

**Comment by billyshena** [comment]
@elswenson Indeed, works fine now if I change those settings in my webpack config 👍 
Thanks !

**Comment by ericyang89** [comment]
why i did find the config file? how can i config it?
