### ISSUE TITLE
Server side rendering (SSR)

### ISSUE THREAD

**Issue by thomaschaaf** [mxstbr/react-boilerplate#92]
I would love to see server side rendering in this boilerplate. This would help SEO and initial page load speed could be increased.

This pretty recent article shows how this could be implemented.
https://medium.com/@MoBinni/a-modern-isomorphic-stack-6609c7c9d057#.xz4r6dzd5

**Comment by mxstbr** [comment]
This is something I'm definitely interested in, but can't at the moment pursue because I'm hard at work with v3. I'll close this issue, but it's on my roadmap to check it out, thank you very much for reminding me!

----

If somebody wants to submit a PR I'd love to have a look at what a react-boilerplate + SSR might look like!

> Note: Please submit the PR against the `v3.0.0` branch if you do so!

**Comment by kachkaev** [comment]
Further discussion: https://github.com/mxstbr/react-boilerplate/pull/625 (for those who landed here from search).
