### ISSUE TITLE
Convention to have component styles defined in .css and be overridable through props

### ISSUE THREAD

**Issue by hendrikswan** [mxstbr/react-boilerplate#981]
Let's say I've got two components, Button and LoginButton. I want to have my css defined inside of style.css files for my components. But I want the more generic component's (Button) styles, to be overridden by my more specific component, also getting it's style from an imported .css file. 

Because with the default name spaced styles that comes with react-boilerplate, we get access only to the generated class name, I came up with a clumsy solution where I combine the classnames. 

So something like this: 

## components/Button/styles.css
```css
.button {
  color: red;
  font-size: 18px;
} 
```

## Button.js 
```javascript
import styles from './styles.css';
import classNames from 'classnames';

function Button({ text, overrideClass }) {
  return <div className={classNames(styles.button, overrideClass)}>{text}</div>;
}
```

## components/LoginButton/styles.css
```css
.loginButton {
  color: red;
} 
```

## LoginButton.js 
```javascript
import styles from './styles.css';
import Button from '../Button';

function LoginButton({ text }) {
  return <Button overrideClass={styles.loginButton}>{text}</div>;
}
```

This works, albeit sometimes with quirky behaviour, depending on which component was loaded first into the resulting DLL (generated by route). 

But I dunno... I don't really like it, it seems overly complex. 

**My question is:**

Is there a nice convention in react-boilerplate to author generic components with overridable style while still keeping all style definition  in .css files?

**Comment by mxstbr** [comment]
Sadly, this isn't really a solved problem in the react world yet. 😢

I wish I had a better answer, but `classnames` is the current standard approach that we use. It's admittedly not very nice and is pretty complex for a seemingly simple task. (sorry @JedWatson)

Sorry!

**Comment by peter-mouland** [comment]
If i understand correctly, the only thing that would need to change would be to append the className rather than replace.

i.e.
` const className = props.className ? props.className : styles.button;`
becomes, as you suggest;
`const className = classNames(styles.button, className)`

so this is an example of a simple button component might look:
```js
export const Button = ({className, children, ...props}) => {
  const classes = classNames(styles.button, className);
  const tag = this.props.href ? 'a' : 'button';
  const buttonProps = {className: classes, ...props};
  return React.createElement(tag, buttonProps, children);
};
```

this way there is nothing the user/dev has to learn to re-use the component

```jsx
<Button className="my-class-name" onClick={myOnClick} >{text}</Button>
```


but, In your example you mention `text` as a prop. I would keep to `children` so that it can be used _naturally_ like other components. and ensure that you _append_ className.

i.e.
```jsx
import styles from './styles.css';
import Button from '../Button';

function LoginButton({ className, children, ...props }) {
  const classNames = classnames(styles.loginButton, className);
  return <Button overrideClass={styles.loginButton} {...props}>{children}</div>;
}
```

You'll notice how i've add `{...props}`. This helps ensure things like `onClick` or `id` etc always come for free.

I use this convention (separating children, appending classNames and destructuring ...props) in all components, which makes them really quite flexible.

hope I didn't go too off topic!
