### ISSUE TITLE
Problem with integrating Semantic UI

### ISSUE THREAD

**Issue by kfrajtak** [mxstbr/react-boilerplate#999]
## Issue Type

Integration bug - problem with adding [Semantic UI](https://github.com/TechnologyAdvice/stardust) components.

## Description

When I try to import Semantic UI component from `stardust` 
```
import { Icon } from 'stardust';
```

I am getting following error (actually two errors, one as listed, the other one with `net` module). 

```
ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'fs' in 'react-boilerplate\node_modules\debug'
 @ ./~/debug/node.js 170:16-30
 @ ./~/stardust/dist/lib/debug.js
 @ ./~/stardust/dist/lib/index.js
 @ ./~/stardust/dist/elements/Button/Button.js
 @ ./~/stardust/dist/elements/index.js
 @ ./~/stardust/dist/addons/Confirm/Confirm.js
 @ ./~/stardust/dist/addons/index.js
 @ ./~/stardust/dist/index.js
 @ ./app/containers/HomePage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main
```

I don't think this is an issue in your code, but I don't know how to debug it since webpack is a black box to me and I don't know why `fs` module is required in the browser. And also the chunks are not debuggable as well.

Also when the web is running, the error message is also displayed in browser window
![image](https://cloud.githubusercontent.com/assets/1510452/18610957/fd916e5e-7d2a-11e6-8ee4-ffc831d0d430.png). 

But when the server is restarted `Not found` message is displayed in the browser window.

## Steps to reproduce

- git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
- cd react-boilerplate
- npm run setup
- npm install stardust --save-dev
- edit app\containers\HomePage\index.js, add 
`import { Icon } from 'stardust';`

# Versions

- Node/NPM: 6.3.0/3.10.3
- Browser: Chrome 52.0.2743.116 m

Customizing webpack config as follows did not help
```
module.exports = (options) => ({
  ...
  node: {
    fs: 'empty',
    net: 'empty',
  }
  ...
}),
```

Any help will be appreciated, thank you.

Karel

**Comment by gihrig** [comment]
Hi @kfrajtak by any chance did you try any of the Stardust [examples](https://github.com/TechnologyAdvice/stardust/tree/master/docs/app/Examples)?

Just to establish a baseline...

**Comment by kfrajtak** [comment]
I had another look at it and after hacking the NPM module debug node.js file it works now. Which is strange since browser debug is referencing the node debug file. I will take it to the stardust repo.
Thanks anyway.

**Comment by martinsimonovski** [comment]
@kfrajtak, I am interested how did you hack the node.js file? Thx

**Comment by kfrajtak** [comment]
I had to remove all `require` statements first and remove everything using those imported modules that was invoked immediately. I left the functions untouched (mostly) and left the `log` function empty.

See the [gist](https://gist.github.com/kfrajtak/3d0404becae047294f29573e33bda0a0) I created.

**Comment by martinsimonovski** [comment]
@kfrajtak I don't know if hacking the node.js is the right thing to do, but after googling for a while 
I found this https://github.com/hallister/semantic-react and can tell you that it works. So probably the error is in the **stardust** .

**Comment by dantedubon** [comment]
I have the same issue than @kfrajtak. The solution provided by him works well....but is not the ideal. If for some reason I make a require('debug') in any part of my app I have the same error that happens with Stardust. I have used Stardust with create-react-app with out any issues.  So, probably it's something related with this project.

**Comment by andrew-oneill** [comment]
I also receive this error when trying to use [https://github.com/TechnologyAdvice/stardust](https://github.com/TechnologyAdvice/stardust) (soon to be renamed semantic-ui-react and officially incorporated under the semantic-ui org). When excluding the `node` key from the webpack config I receive the following terminal error:
```javascript
webpack built 75a862638df740da0ee4 in 10784ms

ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'fs' in '/Users/andrewoneill/repos/kanban-reactboil/node_modules/debug'
 @ ./~/debug/node.js 163:15-28
 @ ./~/semantic-ui-react/dist/commonjs/lib/debug.js
 @ ./~/semantic-ui-react/dist/commonjs/lib/index.js
 @ ./~/semantic-ui-react/dist/commonjs/addons/Confirm/Confirm.js
 @ ./~/semantic-ui-react/dist/commonjs/addons/index.js
 @ ./~/semantic-ui-react/dist/commonjs/index.js
 @ ./app/components/Lane/index.js
 @ ./app/containers/HomePage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main

ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'net' in '/Users/andrewoneill/repos/kanban-reactboil/node_modules/debug'
 @ ./~/debug/node.js 170:16-30
 @ ./~/semantic-ui-react/dist/commonjs/lib/debug.js
 @ ./~/semantic-ui-react/dist/commonjs/lib/index.js
 @ ./~/semantic-ui-react/dist/commonjs/addons/Confirm/Confirm.js
 @ ./~/semantic-ui-react/dist/commonjs/addons/index.js
 @ ./~/semantic-ui-react/dist/commonjs/index.js
 @ ./app/components/Lane/index.js
 @ ./app/containers/HomePage/index.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main
Child html-webpack-plugin for "index.html":
```
When I add the `node` key to the webpack config (in internals/webpack/webpack.base.babel.js) as: 
```javascript
node: {
    fs: 'empty',
    net: 'empty'
}
```
the bundle compiles, but in the browser the following error is logged in the console: 
```javascript
?d41d:10
Dynamic page loading failed SyntaxError: Unexpected token :
    at Object.<anonymous> (0.chunk.js:1168)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at eval (eval at <anonymous> (0.chunk.js:2039), <anonymous>:12:12)
    at Object.<anonymous> (0.chunk.js:2039)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at eval (eval at <anonymous> (0.chunk.js:16), <anonymous>:56:14)
    at Object.<anonymous> (0.chunk.js:16)
    at __webpack_require__ (main.js:681)

node.js?dbc5:122
Uncaught (in promise) SyntaxError: Unexpected token :
    at Object.<anonymous> (0.chunk.js:1168)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at eval (eval at <anonymous> (0.chunk.js:2039), <anonymous>:12:12)
    at Object.<anonymous> (0.chunk.js:2039)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at eval (eval at <anonymous> (0.chunk.js:16), <anonymous>:56:14)
    at Object.<anonymous> (0.chunk.js:16)
    at __webpack_require__ (main.js:681)
```
Clicking on `node.js?dbc5:122` to inspect the source reveals the error to occur in the Node.js debug module as @kfrajtak mentioned.

Adding `console: true` to the node key so that it is:
```javascript
node: {
    console: true,
    fs: 'empty',
    net: 'empty'
}
```
resolves the previous error but now displays a new error in relation to the `assert` module when trying to use utils:
```javascript
assert.js?9281:160
Uncaught TypeError: util.inherits is not a function
    at Object.eval (eval at <anonymous> (main.js:1415), <anonymous>:160:6)
    at eval (eval at <anonymous> (main.js:1415), <anonymous>:492:30)
    at Object.<anonymous> (main.js:1415)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at Object.eval (eval at <anonymous> (main.js:782), <anonymous>:3:14)
    at eval (eval at <anonymous> (main.js:782), <anonymous>:88:30)
    at Object.<anonymous> (main.js:782)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
```
The closest thing I could find for this error was a webpack issue whereby a similar error occurred due to a circular reference between console and assert modules when requiring the request-promise module in webpack/webpack#1019. It was worked around by creating a stub console object, but that doesn't seem like the best solution.

Although this issue is to do with stardust, as @dantedubon mentioned stardust works with other boilerplates. As such I replied to this issue rather than in the stardust repo. I'll likely switch to a different ui library to avoid the issue but I wanted to document my experience here for anyone else who is able to dig in further.

**Comment by simonacca** [comment]
Two bugs here:

The one reported by @kfrajtak i believe is related to the `fs`  module now being integrate into node core,
so updating npm to 3.10.8 solved the issue for me.

The bug reported by @andrew-oneill instead seems related to [this webpack plugin](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L68-L72).

In particular, `process.env` and  `{"NODE_ENV":...}` are not semantically equivalent and cannot be interchanged, this throws an error when `delete process.env.DEBUG;` becomes ` delete {"NODE_ENV":undefined}.DEBUG;` which correctly throws a syntax error.

[This](https://github.com/visionmedia/debug/blob/master/node.js#L120) is where the problem lies in the debug module.

The workaround for me at the moment is to comment out the [plugin](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L68-L72) and rebuild the DLLs ( `npm run build:dll` ).

**Comment by tpinne** [comment]
I can't get around these problems. I still have the same issues as @andrew-oneill with latest node and npm versions and 3.2.1 of this boilerplate.
I followed each process and workaround from @simonacca . Any hints what's missing?

**Comment by tpinne** [comment]
Just tried latest boilerplate release with latest release of semantic-ui-react with node 7.2.0 and npm 3.10.9 and it works with no changes at all.
